package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValue;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValueExample;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValueKey;

public interface BCActCryptoValueMapper extends StaticTableDaoSupport<BCActCryptoValue, BCActCryptoValueExample, BCActCryptoValueKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @SelectProvider(type=BCActCryptoValueSqlProvider.class, method="countByExample")
    int countByExample(BCActCryptoValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @DeleteProvider(type=BCActCryptoValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCActCryptoValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Delete({
        "delete from BC_ACT_CRYPTO_VALUE",
        "where ACTV_UID = #{actvUid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCActCryptoValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Insert({
        "insert into BC_ACT_CRYPTO_VALUE (ACTV_UID, ACTV_HASH, ",
        "ACT_ADDRESS, ACTV_OWNER, ",
        "ACTV_NAME, ACTV_CODE, ",
        "ACTV_NONCE, ACTV_TIMESTAMP, ",
        "ACTV_OWNERTIME, ACTV_INDEX, ",
        "ACTV_TOTAL, DATA_HEX, ",
        "ACTV_STATUS, CREATE_TIME, ",
        "UPDATE_TIME)",
        "values (#{actvUid,jdbcType=VARCHAR}, #{actvHash,jdbcType=VARCHAR}, ",
        "#{actAddress,jdbcType=VARCHAR}, #{actvOwner,jdbcType=VARCHAR}, ",
        "#{actvName,jdbcType=VARCHAR}, #{actvCode,jdbcType=VARCHAR}, ",
        "#{actvNonce,jdbcType=INTEGER}, #{actvTimestamp,jdbcType=DECIMAL}, ",
        "#{actvOwnertime,jdbcType=DECIMAL}, #{actvIndex,jdbcType=DECIMAL}, ",
        "#{actvTotal,jdbcType=DECIMAL}, #{dataHex,jdbcType=VARCHAR}, ",
        "#{actvStatus,jdbcType=CHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCActCryptoValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @InsertProvider(type=BCActCryptoValueSqlProvider.class, method="insertSelective")
    int insertSelective(BCActCryptoValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @SelectProvider(type=BCActCryptoValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ACTV_UID", property="actvUid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ACTV_HASH", property="actvHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_ADDRESS", property="actAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_OWNER", property="actvOwner", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_NAME", property="actvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_CODE", property="actvCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_NONCE", property="actvNonce", jdbcType=JdbcType.INTEGER),
        @Result(column="ACTV_TIMESTAMP", property="actvTimestamp", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_OWNERTIME", property="actvOwnertime", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_INDEX", property="actvIndex", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_TOTAL", property="actvTotal", jdbcType=JdbcType.DECIMAL),
        @Result(column="DATA_HEX", property="dataHex", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_STATUS", property="actvStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCActCryptoValue> selectByExample(BCActCryptoValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Select({
        "select",
        "ACTV_UID, ACTV_HASH, ACT_ADDRESS, ACTV_OWNER, ACTV_NAME, ACTV_CODE, ACTV_NONCE, ",
        "ACTV_TIMESTAMP, ACTV_OWNERTIME, ACTV_INDEX, ACTV_TOTAL, DATA_HEX, ACTV_STATUS, ",
        "CREATE_TIME, UPDATE_TIME",
        "from BC_ACT_CRYPTO_VALUE",
        "where ACTV_UID = #{actvUid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ACTV_UID", property="actvUid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ACTV_HASH", property="actvHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACT_ADDRESS", property="actAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_OWNER", property="actvOwner", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_NAME", property="actvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_CODE", property="actvCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_NONCE", property="actvNonce", jdbcType=JdbcType.INTEGER),
        @Result(column="ACTV_TIMESTAMP", property="actvTimestamp", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_OWNERTIME", property="actvOwnertime", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_INDEX", property="actvIndex", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_TOTAL", property="actvTotal", jdbcType=JdbcType.DECIMAL),
        @Result(column="DATA_HEX", property="dataHex", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_STATUS", property="actvStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCActCryptoValue selectByPrimaryKey(BCActCryptoValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @UpdateProvider(type=BCActCryptoValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCActCryptoValue record, @Param("example") BCActCryptoValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @UpdateProvider(type=BCActCryptoValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCActCryptoValue record, @Param("example") BCActCryptoValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @UpdateProvider(type=BCActCryptoValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCActCryptoValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Update({
        "update BC_ACT_CRYPTO_VALUE",
        "set ACTV_HASH = #{actvHash,jdbcType=VARCHAR},",
          "ACT_ADDRESS = #{actAddress,jdbcType=VARCHAR},",
          "ACTV_OWNER = #{actvOwner,jdbcType=VARCHAR},",
          "ACTV_NAME = #{actvName,jdbcType=VARCHAR},",
          "ACTV_CODE = #{actvCode,jdbcType=VARCHAR},",
          "ACTV_NONCE = #{actvNonce,jdbcType=INTEGER},",
          "ACTV_TIMESTAMP = #{actvTimestamp,jdbcType=DECIMAL},",
          "ACTV_OWNERTIME = #{actvOwnertime,jdbcType=DECIMAL},",
          "ACTV_INDEX = #{actvIndex,jdbcType=DECIMAL},",
          "ACTV_TOTAL = #{actvTotal,jdbcType=DECIMAL},",
          "DATA_HEX = #{dataHex,jdbcType=VARCHAR},",
          "ACTV_STATUS = #{actvStatus,jdbcType=CHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ACTV_UID = #{actvUid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCActCryptoValue record);
}