package org.brewchain.backend.ordbgens.bc.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.backend.ordbgens.bc.entity.BCAccount;
import org.brewchain.backend.ordbgens.bc.entity.BCAccountExample.Criteria;
import org.brewchain.backend.ordbgens.bc.entity.BCAccountExample.Criterion;
import org.brewchain.backend.ordbgens.bc.entity.BCAccountExample;

public class BCAccountSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String countByExample(BCAccountExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("BC_ACCOUNT");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String deleteByExample(BCAccountExample example) {
        BEGIN();
        DELETE_FROM("BC_ACCOUNT");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String insertSelective(BCAccount record) {
        BEGIN();
        INSERT_INTO("BC_ACCOUNT");
        
        if (record.getActAddress() != null) {
            VALUES("ACT_ADDRESS", "#{actAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getActNonce() != null) {
            VALUES("ACT_NONCE", "#{actNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActBalance() != null) {
            VALUES("ACT_BALANCE", "#{actBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getActMax() != null) {
            VALUES("ACT_MAX", "#{actMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptMax() != null) {
            VALUES("ACT_ACCEPT_MAX", "#{actAcceptMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptLimit() != null) {
            VALUES("ACT_ACCEPT_LIMIT", "#{actAcceptLimit,jdbcType=DECIMAL}");
        }
        
        if (record.getStorageHex() != null) {
            VALUES("STORAGE_HEX", "#{storageHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHashHex() != null) {
            VALUES("CODE_HASH_HEX", "#{codeHashHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHex() != null) {
            VALUES("CODE_HEX", "#{codeHex,jdbcType=VARCHAR}");
        }
        
        if (record.getDataHex() != null) {
            VALUES("DATA_HEX", "#{dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActStatus() != null) {
            VALUES("ACT_STATUS", "#{actStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String selectByExample(BCAccountExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ACT_ADDRESS");
        } else {
            SELECT("ACT_ADDRESS");
        }
        SELECT("ACT_NONCE");
        SELECT("ACT_BALANCE");
        SELECT("ACT_MAX");
        SELECT("ACT_ACCEPT_MAX");
        SELECT("ACT_ACCEPT_LIMIT");
        SELECT("STORAGE_HEX");
        SELECT("CODE_HASH_HEX");
        SELECT("CODE_HEX");
        SELECT("DATA_HEX");
        SELECT("ACT_STATUS");
        SELECT("CREATE_TIME");
        SELECT("UPDATE_TIME");
        FROM("BC_ACCOUNT");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("BC_ACCOUNT");				applyWhere(example, false);
		}
        if(example != null){
            String sql = SQL();

            if(example.getGroupByClause()!=null&&example.getGroupByClause().trim().length()>0)  sql=sql.concat("group by ").concat(example.getGroupByClause());
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= sql.concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return sql+"  FOR UPDATE " ;  }
                
		return sql;}

                return SQL();
            }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BCAccount record = (BCAccount) parameter.get("record");
        BCAccountExample example = (BCAccountExample) parameter.get("example");
        
        BEGIN();
        UPDATE("BC_ACCOUNT");
        
        if (record.getActAddress() != null) {
            SET("ACT_ADDRESS = #{record.actAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getActNonce() != null) {
            SET("ACT_NONCE = #{record.actNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActBalance() != null) {
            SET("ACT_BALANCE = #{record.actBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getActMax() != null) {
            SET("ACT_MAX = #{record.actMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptMax() != null) {
            SET("ACT_ACCEPT_MAX = #{record.actAcceptMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptLimit() != null) {
            SET("ACT_ACCEPT_LIMIT = #{record.actAcceptLimit,jdbcType=DECIMAL}");
        }
        
        if (record.getStorageHex() != null) {
            SET("STORAGE_HEX = #{record.storageHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHashHex() != null) {
            SET("CODE_HASH_HEX = #{record.codeHashHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHex() != null) {
            SET("CODE_HEX = #{record.codeHex,jdbcType=VARCHAR}");
        }
        
        if (record.getDataHex() != null) {
            SET("DATA_HEX = #{record.dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActStatus() != null) {
            SET("ACT_STATUS = #{record.actStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("BC_ACCOUNT");
        
        SET("ACT_ADDRESS = #{record.actAddress,jdbcType=VARCHAR}");
        SET("ACT_NONCE = #{record.actNonce,jdbcType=INTEGER}");
        SET("ACT_BALANCE = #{record.actBalance,jdbcType=DECIMAL}");
        SET("ACT_MAX = #{record.actMax,jdbcType=DECIMAL}");
        SET("ACT_ACCEPT_MAX = #{record.actAcceptMax,jdbcType=DECIMAL}");
        SET("ACT_ACCEPT_LIMIT = #{record.actAcceptLimit,jdbcType=DECIMAL}");
        SET("STORAGE_HEX = #{record.storageHex,jdbcType=VARCHAR}");
        SET("CODE_HASH_HEX = #{record.codeHashHex,jdbcType=VARCHAR}");
        SET("CODE_HEX = #{record.codeHex,jdbcType=VARCHAR}");
        SET("DATA_HEX = #{record.dataHex,jdbcType=VARCHAR}");
        SET("ACT_STATUS = #{record.actStatus,jdbcType=CHAR}");
        SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        BCAccountExample example = (BCAccountExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByPrimaryKeySelective(BCAccount record) {
        BEGIN();
        UPDATE("BC_ACCOUNT");
        
        if (record.getActNonce() != null) {
            SET("ACT_NONCE = #{actNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActBalance() != null) {
            SET("ACT_BALANCE = #{actBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getActMax() != null) {
            SET("ACT_MAX = #{actMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptMax() != null) {
            SET("ACT_ACCEPT_MAX = #{actAcceptMax,jdbcType=DECIMAL}");
        }
        
        if (record.getActAcceptLimit() != null) {
            SET("ACT_ACCEPT_LIMIT = #{actAcceptLimit,jdbcType=DECIMAL}");
        }
        
        if (record.getStorageHex() != null) {
            SET("STORAGE_HEX = #{storageHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHashHex() != null) {
            SET("CODE_HASH_HEX = #{codeHashHex,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeHex() != null) {
            SET("CODE_HEX = #{codeHex,jdbcType=VARCHAR}");
        }
        
        if (record.getDataHex() != null) {
            SET("DATA_HEX = #{dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActStatus() != null) {
            SET("ACT_STATUS = #{actStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("ACT_ADDRESS = #{actAddress,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    protected void applyWhere(BCAccountExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}