package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCActTokenValue;
import org.brewchain.backend.ordbgens.bc.entity.BCActTokenValueExample;
import org.brewchain.backend.ordbgens.bc.entity.BCActTokenValueKey;

public interface BCActTokenValueMapper extends StaticTableDaoSupport<BCActTokenValue, BCActTokenValueExample, BCActTokenValueKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCActTokenValueSqlProvider.class, method="countByExample")
    int countByExample(BCActTokenValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @DeleteProvider(type=BCActTokenValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCActTokenValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Delete({
        "delete from BC_ACT_TOKEN_VALUE",
        "where ACTV_TOKEN_ID = #{actvTokenId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCActTokenValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Insert({
        "insert into BC_ACT_TOKEN_VALUE (ACTV_TOKEN_ID, ACT_ADDRESS, ",
        "ACTV_TOKEN, ACTV_BALANCE, ",
        "ACTV_LOCKED, ACTT_STATUS, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{actvTokenId,jdbcType=VARCHAR}, #{actAddress,jdbcType=VARCHAR}, ",
        "#{actvToken,jdbcType=VARCHAR}, #{actvBalance,jdbcType=DECIMAL}, ",
        "#{actvLocked,jdbcType=DECIMAL}, #{acttStatus,jdbcType=CHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCActTokenValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @InsertProvider(type=BCActTokenValueSqlProvider.class, method="insertSelective")
    int insertSelective(BCActTokenValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCActTokenValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ACTV_TOKEN_ID", property="actvTokenId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ACT_ADDRESS", property="actAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_TOKEN", property="actvToken", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_BALANCE", property="actvBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_LOCKED", property="actvLocked", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTT_STATUS", property="acttStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCActTokenValue> selectByExample(BCActTokenValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Select({
        "select",
        "ACTV_TOKEN_ID, ACT_ADDRESS, ACTV_TOKEN, ACTV_BALANCE, ACTV_LOCKED, ACTT_STATUS, ",
        "CREATE_TIME, UPDATE_TIME",
        "from BC_ACT_TOKEN_VALUE",
        "where ACTV_TOKEN_ID = #{actvTokenId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ACTV_TOKEN_ID", property="actvTokenId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ACT_ADDRESS", property="actAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_TOKEN", property="actvToken", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTV_BALANCE", property="actvBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTV_LOCKED", property="actvLocked", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACTT_STATUS", property="acttStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCActTokenValue selectByPrimaryKey(BCActTokenValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCActTokenValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCActTokenValue record, @Param("example") BCActTokenValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCActTokenValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCActTokenValue record, @Param("example") BCActTokenValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCActTokenValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCActTokenValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Update({
        "update BC_ACT_TOKEN_VALUE",
        "set ACT_ADDRESS = #{actAddress,jdbcType=VARCHAR},",
          "ACTV_TOKEN = #{actvToken,jdbcType=VARCHAR},",
          "ACTV_BALANCE = #{actvBalance,jdbcType=DECIMAL},",
          "ACTV_LOCKED = #{actvLocked,jdbcType=DECIMAL},",
          "ACTT_STATUS = #{acttStatus,jdbcType=CHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ACTV_TOKEN_ID = #{actvTokenId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCActTokenValue record);
}