package org.brewchain.backend.ordbgens.bc.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValue;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValueExample.Criteria;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValueExample.Criterion;
import org.brewchain.backend.ordbgens.bc.entity.BCActCryptoValueExample;

public class BCActCryptoValueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String countByExample(BCActCryptoValueExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("BC_ACT_CRYPTO_VALUE");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String deleteByExample(BCActCryptoValueExample example) {
        BEGIN();
        DELETE_FROM("BC_ACT_CRYPTO_VALUE");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String insertSelective(BCActCryptoValue record) {
        BEGIN();
        INSERT_INTO("BC_ACT_CRYPTO_VALUE");
        
        if (record.getActvUid() != null) {
            VALUES("ACTV_UID", "#{actvUid,jdbcType=VARCHAR}");
        }
        
        if (record.getActvHash() != null) {
            VALUES("ACTV_HASH", "#{actvHash,jdbcType=VARCHAR}");
        }
        
        if (record.getActAddress() != null) {
            VALUES("ACT_ADDRESS", "#{actAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getActvOwner() != null) {
            VALUES("ACTV_OWNER", "#{actvOwner,jdbcType=VARCHAR}");
        }
        
        if (record.getActvName() != null) {
            VALUES("ACTV_NAME", "#{actvName,jdbcType=VARCHAR}");
        }
        
        if (record.getActvCode() != null) {
            VALUES("ACTV_CODE", "#{actvCode,jdbcType=VARCHAR}");
        }
        
        if (record.getActvNonce() != null) {
            VALUES("ACTV_NONCE", "#{actvNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActvTimestamp() != null) {
            VALUES("ACTV_TIMESTAMP", "#{actvTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getActvOwnertime() != null) {
            VALUES("ACTV_OWNERTIME", "#{actvOwnertime,jdbcType=DECIMAL}");
        }
        
        if (record.getActvIndex() != null) {
            VALUES("ACTV_INDEX", "#{actvIndex,jdbcType=DECIMAL}");
        }
        
        if (record.getActvTotal() != null) {
            VALUES("ACTV_TOTAL", "#{actvTotal,jdbcType=DECIMAL}");
        }
        
        if (record.getDataHex() != null) {
            VALUES("DATA_HEX", "#{dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActvStatus() != null) {
            VALUES("ACTV_STATUS", "#{actvStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String selectByExample(BCActCryptoValueExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ACTV_UID");
        } else {
            SELECT("ACTV_UID");
        }
        SELECT("ACTV_HASH");
        SELECT("ACT_ADDRESS");
        SELECT("ACTV_OWNER");
        SELECT("ACTV_NAME");
        SELECT("ACTV_CODE");
        SELECT("ACTV_NONCE");
        SELECT("ACTV_TIMESTAMP");
        SELECT("ACTV_OWNERTIME");
        SELECT("ACTV_INDEX");
        SELECT("ACTV_TOTAL");
        SELECT("DATA_HEX");
        SELECT("ACTV_STATUS");
        SELECT("CREATE_TIME");
        SELECT("UPDATE_TIME");
        FROM("BC_ACT_CRYPTO_VALUE");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("BC_ACT_CRYPTO_VALUE");				applyWhere(example, false);
		}
        if(example != null){
            String sql = SQL();

            if(example.getGroupByClause()!=null&&example.getGroupByClause().trim().length()>0)  sql=sql.concat("group by ").concat(example.getGroupByClause());
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= sql.concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return sql+"  FOR UPDATE " ;  }
                
		return sql;}

                return SQL();
            }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BCActCryptoValue record = (BCActCryptoValue) parameter.get("record");
        BCActCryptoValueExample example = (BCActCryptoValueExample) parameter.get("example");
        
        BEGIN();
        UPDATE("BC_ACT_CRYPTO_VALUE");
        
        if (record.getActvUid() != null) {
            SET("ACTV_UID = #{record.actvUid,jdbcType=VARCHAR}");
        }
        
        if (record.getActvHash() != null) {
            SET("ACTV_HASH = #{record.actvHash,jdbcType=VARCHAR}");
        }
        
        if (record.getActAddress() != null) {
            SET("ACT_ADDRESS = #{record.actAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getActvOwner() != null) {
            SET("ACTV_OWNER = #{record.actvOwner,jdbcType=VARCHAR}");
        }
        
        if (record.getActvName() != null) {
            SET("ACTV_NAME = #{record.actvName,jdbcType=VARCHAR}");
        }
        
        if (record.getActvCode() != null) {
            SET("ACTV_CODE = #{record.actvCode,jdbcType=VARCHAR}");
        }
        
        if (record.getActvNonce() != null) {
            SET("ACTV_NONCE = #{record.actvNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActvTimestamp() != null) {
            SET("ACTV_TIMESTAMP = #{record.actvTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getActvOwnertime() != null) {
            SET("ACTV_OWNERTIME = #{record.actvOwnertime,jdbcType=DECIMAL}");
        }
        
        if (record.getActvIndex() != null) {
            SET("ACTV_INDEX = #{record.actvIndex,jdbcType=DECIMAL}");
        }
        
        if (record.getActvTotal() != null) {
            SET("ACTV_TOTAL = #{record.actvTotal,jdbcType=DECIMAL}");
        }
        
        if (record.getDataHex() != null) {
            SET("DATA_HEX = #{record.dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActvStatus() != null) {
            SET("ACTV_STATUS = #{record.actvStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("BC_ACT_CRYPTO_VALUE");
        
        SET("ACTV_UID = #{record.actvUid,jdbcType=VARCHAR}");
        SET("ACTV_HASH = #{record.actvHash,jdbcType=VARCHAR}");
        SET("ACT_ADDRESS = #{record.actAddress,jdbcType=VARCHAR}");
        SET("ACTV_OWNER = #{record.actvOwner,jdbcType=VARCHAR}");
        SET("ACTV_NAME = #{record.actvName,jdbcType=VARCHAR}");
        SET("ACTV_CODE = #{record.actvCode,jdbcType=VARCHAR}");
        SET("ACTV_NONCE = #{record.actvNonce,jdbcType=INTEGER}");
        SET("ACTV_TIMESTAMP = #{record.actvTimestamp,jdbcType=DECIMAL}");
        SET("ACTV_OWNERTIME = #{record.actvOwnertime,jdbcType=DECIMAL}");
        SET("ACTV_INDEX = #{record.actvIndex,jdbcType=DECIMAL}");
        SET("ACTV_TOTAL = #{record.actvTotal,jdbcType=DECIMAL}");
        SET("DATA_HEX = #{record.dataHex,jdbcType=VARCHAR}");
        SET("ACTV_STATUS = #{record.actvStatus,jdbcType=CHAR}");
        SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        BCActCryptoValueExample example = (BCActCryptoValueExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String updateByPrimaryKeySelective(BCActCryptoValue record) {
        BEGIN();
        UPDATE("BC_ACT_CRYPTO_VALUE");
        
        if (record.getActvHash() != null) {
            SET("ACTV_HASH = #{actvHash,jdbcType=VARCHAR}");
        }
        
        if (record.getActAddress() != null) {
            SET("ACT_ADDRESS = #{actAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getActvOwner() != null) {
            SET("ACTV_OWNER = #{actvOwner,jdbcType=VARCHAR}");
        }
        
        if (record.getActvName() != null) {
            SET("ACTV_NAME = #{actvName,jdbcType=VARCHAR}");
        }
        
        if (record.getActvCode() != null) {
            SET("ACTV_CODE = #{actvCode,jdbcType=VARCHAR}");
        }
        
        if (record.getActvNonce() != null) {
            SET("ACTV_NONCE = #{actvNonce,jdbcType=INTEGER}");
        }
        
        if (record.getActvTimestamp() != null) {
            SET("ACTV_TIMESTAMP = #{actvTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getActvOwnertime() != null) {
            SET("ACTV_OWNERTIME = #{actvOwnertime,jdbcType=DECIMAL}");
        }
        
        if (record.getActvIndex() != null) {
            SET("ACTV_INDEX = #{actvIndex,jdbcType=DECIMAL}");
        }
        
        if (record.getActvTotal() != null) {
            SET("ACTV_TOTAL = #{actvTotal,jdbcType=DECIMAL}");
        }
        
        if (record.getDataHex() != null) {
            SET("DATA_HEX = #{dataHex,jdbcType=VARCHAR}");
        }
        
        if (record.getActvStatus() != null) {
            SET("ACTV_STATUS = #{actvStatus,jdbcType=CHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("ACTV_UID = #{actvUid,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    protected void applyWhere(BCActCryptoValueExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}