package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCBlockMpt;
import org.brewchain.backend.ordbgens.bc.entity.BCBlockMptExample;
import org.brewchain.backend.ordbgens.bc.entity.BCBlockMptKey;

public interface BCBlockMptMapper extends StaticTableDaoSupport<BCBlockMpt, BCBlockMptExample, BCBlockMptKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCBlockMptSqlProvider.class, method="countByExample")
    int countByExample(BCBlockMptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @DeleteProvider(type=BCBlockMptSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCBlockMptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Delete({
        "delete from BC_BLOCK_MPT",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCBlockMptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Insert({
        "insert into BC_BLOCK_MPT (LOG_UUID, BVERSION, ",
        "BLOCK_HEIGHT, HASH_MPT, ",
        "HASH_PREV_MPT, MPT_TYPE, ",
        "VALUE_COUNTS, BLOCK_STATUS, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{logUuid,jdbcType=VARCHAR}, #{bversion,jdbcType=VARCHAR}, ",
        "#{blockHeight,jdbcType=DECIMAL}, #{hashMpt,jdbcType=VARCHAR}, ",
        "#{hashPrevMpt,jdbcType=VARCHAR}, #{mptType,jdbcType=VARCHAR}, ",
        "#{valueCounts,jdbcType=INTEGER}, #{blockStatus,jdbcType=CHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCBlockMpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @InsertProvider(type=BCBlockMptSqlProvider.class, method="insertSelective")
    int insertSelective(BCBlockMpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCBlockMptSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_HEIGHT", property="blockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="HASH_MPT", property="hashMpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="HASH_PREV_MPT", property="hashPrevMpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="MPT_TYPE", property="mptType", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALUE_COUNTS", property="valueCounts", jdbcType=JdbcType.INTEGER),
        @Result(column="BLOCK_STATUS", property="blockStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCBlockMpt> selectByExample(BCBlockMptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Select({
        "select",
        "LOG_UUID, BVERSION, BLOCK_HEIGHT, HASH_MPT, HASH_PREV_MPT, MPT_TYPE, VALUE_COUNTS, ",
        "BLOCK_STATUS, CREATE_TIME, UPDATE_TIME",
        "from BC_BLOCK_MPT",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_HEIGHT", property="blockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="HASH_MPT", property="hashMpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="HASH_PREV_MPT", property="hashPrevMpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="MPT_TYPE", property="mptType", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALUE_COUNTS", property="valueCounts", jdbcType=JdbcType.INTEGER),
        @Result(column="BLOCK_STATUS", property="blockStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCBlockMpt selectByPrimaryKey(BCBlockMptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockMptSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCBlockMpt record, @Param("example") BCBlockMptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockMptSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCBlockMpt record, @Param("example") BCBlockMptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockMptSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCBlockMpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Update({
        "update BC_BLOCK_MPT",
        "set BVERSION = #{bversion,jdbcType=VARCHAR},",
          "BLOCK_HEIGHT = #{blockHeight,jdbcType=DECIMAL},",
          "HASH_MPT = #{hashMpt,jdbcType=VARCHAR},",
          "HASH_PREV_MPT = #{hashPrevMpt,jdbcType=VARCHAR},",
          "MPT_TYPE = #{mptType,jdbcType=VARCHAR},",
          "VALUE_COUNTS = #{valueCounts,jdbcType=INTEGER},",
          "BLOCK_STATUS = #{blockStatus,jdbcType=CHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCBlockMpt record);
}