package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCBlock;
import org.brewchain.backend.ordbgens.bc.entity.BCBlockExample;
import org.brewchain.backend.ordbgens.bc.entity.BCBlockKey;

public interface BCBlockMapper extends StaticTableDaoSupport<BCBlock, BCBlockExample, BCBlockKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCBlockSqlProvider.class, method="countByExample")
    int countByExample(BCBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @DeleteProvider(type=BCBlockSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Delete({
        "delete from BC_BLOCK",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Insert({
        "insert into BC_BLOCK (LOG_UUID, BVERSION, ",
        "SECOND_IDX, BH_PARENT_HASH, ",
        "BH_STATE_ROOT, BH_BLOCK_HASH, ",
        "BH_TXT_RIEROOT, BH_RECEIPT_TRIEROOT, ",
        "BH_TIMESTAMP, BH_NUMBER, ",
        "BH_TXN_COUNT, BH_SLICEID, ",
        "BH_EXTRADATA, BM_NODE, ",
        "BM_REWARD_HEX, BM_ADDRESS, ",
        "BM_BCUID, BLOCK_STATUS, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{logUuid,jdbcType=VARCHAR}, #{bversion,jdbcType=VARCHAR}, ",
        "#{secondIdx,jdbcType=VARCHAR}, #{bhParentHash,jdbcType=VARCHAR}, ",
        "#{bhStateRoot,jdbcType=VARCHAR}, #{bhBlockHash,jdbcType=VARCHAR}, ",
        "#{bhTxtRieroot,jdbcType=VARCHAR}, #{bhReceiptTrieroot,jdbcType=VARCHAR}, ",
        "#{bhTimestamp,jdbcType=DECIMAL}, #{bhNumber,jdbcType=DECIMAL}, ",
        "#{bhTxnCount,jdbcType=INTEGER}, #{bhSliceid,jdbcType=INTEGER}, ",
        "#{bhExtradata,jdbcType=VARCHAR}, #{bmNode,jdbcType=VARCHAR}, ",
        "#{bmRewardHex,jdbcType=VARCHAR}, #{bmAddress,jdbcType=VARCHAR}, ",
        "#{bmBcuid,jdbcType=VARCHAR}, #{blockStatus,jdbcType=CHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @InsertProvider(type=BCBlockSqlProvider.class, method="insertSelective")
    int insertSelective(BCBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCBlockSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="SECOND_IDX", property="secondIdx", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_PARENT_HASH", property="bhParentHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_STATE_ROOT", property="bhStateRoot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_BLOCK_HASH", property="bhBlockHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_TXT_RIEROOT", property="bhTxtRieroot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_RECEIPT_TRIEROOT", property="bhReceiptTrieroot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_TIMESTAMP", property="bhTimestamp", jdbcType=JdbcType.DECIMAL),
        @Result(column="BH_NUMBER", property="bhNumber", jdbcType=JdbcType.DECIMAL),
        @Result(column="BH_TXN_COUNT", property="bhTxnCount", jdbcType=JdbcType.INTEGER),
        @Result(column="BH_SLICEID", property="bhSliceid", jdbcType=JdbcType.INTEGER),
        @Result(column="BH_EXTRADATA", property="bhExtradata", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_NODE", property="bmNode", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_REWARD_HEX", property="bmRewardHex", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_ADDRESS", property="bmAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_BCUID", property="bmBcuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_STATUS", property="blockStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCBlock> selectByExample(BCBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Select({
        "select",
        "LOG_UUID, BVERSION, SECOND_IDX, BH_PARENT_HASH, BH_STATE_ROOT, BH_BLOCK_HASH, ",
        "BH_TXT_RIEROOT, BH_RECEIPT_TRIEROOT, BH_TIMESTAMP, BH_NUMBER, BH_TXN_COUNT, ",
        "BH_SLICEID, BH_EXTRADATA, BM_NODE, BM_REWARD_HEX, BM_ADDRESS, BM_BCUID, BLOCK_STATUS, ",
        "CREATE_TIME, UPDATE_TIME",
        "from BC_BLOCK",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="SECOND_IDX", property="secondIdx", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_PARENT_HASH", property="bhParentHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_STATE_ROOT", property="bhStateRoot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_BLOCK_HASH", property="bhBlockHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_TXT_RIEROOT", property="bhTxtRieroot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_RECEIPT_TRIEROOT", property="bhReceiptTrieroot", jdbcType=JdbcType.VARCHAR),
        @Result(column="BH_TIMESTAMP", property="bhTimestamp", jdbcType=JdbcType.DECIMAL),
        @Result(column="BH_NUMBER", property="bhNumber", jdbcType=JdbcType.DECIMAL),
        @Result(column="BH_TXN_COUNT", property="bhTxnCount", jdbcType=JdbcType.INTEGER),
        @Result(column="BH_SLICEID", property="bhSliceid", jdbcType=JdbcType.INTEGER),
        @Result(column="BH_EXTRADATA", property="bhExtradata", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_NODE", property="bmNode", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_REWARD_HEX", property="bmRewardHex", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_ADDRESS", property="bmAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="BM_BCUID", property="bmBcuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_STATUS", property="blockStatus", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCBlock selectByPrimaryKey(BCBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCBlock record, @Param("example") BCBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCBlock record, @Param("example") BCBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCBlockSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Update({
        "update BC_BLOCK",
        "set BVERSION = #{bversion,jdbcType=VARCHAR},",
          "SECOND_IDX = #{secondIdx,jdbcType=VARCHAR},",
          "BH_PARENT_HASH = #{bhParentHash,jdbcType=VARCHAR},",
          "BH_STATE_ROOT = #{bhStateRoot,jdbcType=VARCHAR},",
          "BH_BLOCK_HASH = #{bhBlockHash,jdbcType=VARCHAR},",
          "BH_TXT_RIEROOT = #{bhTxtRieroot,jdbcType=VARCHAR},",
          "BH_RECEIPT_TRIEROOT = #{bhReceiptTrieroot,jdbcType=VARCHAR},",
          "BH_TIMESTAMP = #{bhTimestamp,jdbcType=DECIMAL},",
          "BH_NUMBER = #{bhNumber,jdbcType=DECIMAL},",
          "BH_TXN_COUNT = #{bhTxnCount,jdbcType=INTEGER},",
          "BH_SLICEID = #{bhSliceid,jdbcType=INTEGER},",
          "BH_EXTRADATA = #{bhExtradata,jdbcType=VARCHAR},",
          "BM_NODE = #{bmNode,jdbcType=VARCHAR},",
          "BM_REWARD_HEX = #{bmRewardHex,jdbcType=VARCHAR},",
          "BM_ADDRESS = #{bmAddress,jdbcType=VARCHAR},",
          "BM_BCUID = #{bmBcuid,jdbcType=VARCHAR},",
          "BLOCK_STATUS = #{blockStatus,jdbcType=CHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCBlock record);
}