package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCGlobalProps;
import org.brewchain.backend.ordbgens.bc.entity.BCGlobalPropsExample;
import org.brewchain.backend.ordbgens.bc.entity.BCGlobalPropsKey;

public interface BCGlobalPropsMapper extends StaticTableDaoSupport<BCGlobalProps, BCGlobalPropsExample, BCGlobalPropsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCGlobalPropsSqlProvider.class, method="countByExample")
    int countByExample(BCGlobalPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @DeleteProvider(type=BCGlobalPropsSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCGlobalPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Delete({
        "delete from BC_GLOBAL_PROPS",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCGlobalPropsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Insert({
        "insert into BC_GLOBAL_PROPS (LOG_UUID, BVERSION, ",
        "BLOCK_HEIGHT, PROP_KEY, ",
        "PROP_VALUE, MPT_TYPE, ",
        "HASH_VALUE, TXID, ",
        "PREV_HASH_VALUE, PREV_BLOCK_HEIGHT, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{logUuid,jdbcType=VARCHAR}, #{bversion,jdbcType=VARCHAR}, ",
        "#{blockHeight,jdbcType=DECIMAL}, #{propKey,jdbcType=VARCHAR}, ",
        "#{propValue,jdbcType=VARCHAR}, #{mptType,jdbcType=VARCHAR}, ",
        "#{hashValue,jdbcType=VARCHAR}, #{txid,jdbcType=VARCHAR}, ",
        "#{prevHashValue,jdbcType=VARCHAR}, #{prevBlockHeight,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCGlobalProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @InsertProvider(type=BCGlobalPropsSqlProvider.class, method="insertSelective")
    int insertSelective(BCGlobalProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCGlobalPropsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_HEIGHT", property="blockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROP_KEY", property="propKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROP_VALUE", property="propValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="MPT_TYPE", property="mptType", jdbcType=JdbcType.VARCHAR),
        @Result(column="HASH_VALUE", property="hashValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="TXID", property="txid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_HASH_VALUE", property="prevHashValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_BLOCK_HEIGHT", property="prevBlockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCGlobalProps> selectByExample(BCGlobalPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Select({
        "select",
        "LOG_UUID, BVERSION, BLOCK_HEIGHT, PROP_KEY, PROP_VALUE, MPT_TYPE, HASH_VALUE, ",
        "TXID, PREV_HASH_VALUE, PREV_BLOCK_HEIGHT, CREATE_TIME, UPDATE_TIME",
        "from BC_GLOBAL_PROPS",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="BLOCK_HEIGHT", property="blockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROP_KEY", property="propKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROP_VALUE", property="propValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="MPT_TYPE", property="mptType", jdbcType=JdbcType.VARCHAR),
        @Result(column="HASH_VALUE", property="hashValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="TXID", property="txid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_HASH_VALUE", property="prevHashValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_BLOCK_HEIGHT", property="prevBlockHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCGlobalProps selectByPrimaryKey(BCGlobalPropsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCGlobalPropsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCGlobalProps record, @Param("example") BCGlobalPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCGlobalPropsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCGlobalProps record, @Param("example") BCGlobalPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCGlobalPropsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCGlobalProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_GLOBAL_PROPS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Update({
        "update BC_GLOBAL_PROPS",
        "set BVERSION = #{bversion,jdbcType=VARCHAR},",
          "BLOCK_HEIGHT = #{blockHeight,jdbcType=DECIMAL},",
          "PROP_KEY = #{propKey,jdbcType=VARCHAR},",
          "PROP_VALUE = #{propValue,jdbcType=VARCHAR},",
          "MPT_TYPE = #{mptType,jdbcType=VARCHAR},",
          "HASH_VALUE = #{hashValue,jdbcType=VARCHAR},",
          "TXID = #{txid,jdbcType=VARCHAR},",
          "PREV_HASH_VALUE = #{prevHashValue,jdbcType=VARCHAR},",
          "PREV_BLOCK_HEIGHT = #{prevBlockHeight,jdbcType=DECIMAL},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where LOG_UUID = #{logUuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCGlobalProps record);
}