package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxSignature;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxSignatureExample;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxSignatureKey;

public interface BCMtxSignatureMapper extends StaticTableDaoSupport<BCMtxSignature, BCMtxSignatureExample, BCMtxSignatureKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCMtxSignatureSqlProvider.class, method="countByExample")
    int countByExample(BCMtxSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @DeleteProvider(type=BCMtxSignatureSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCMtxSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Delete({
        "delete from BC_MTX_SIGNATURE",
        "where MTX_SIGNID = #{mtxSignid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCMtxSignatureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Insert({
        "insert into BC_MTX_SIGNATURE (MTX_SIGNID, BC_ADDRESS, ",
        "MTX_HASH, SIGN_DATA, ",
        "TX_STATUS, INDEX_IN_TX, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{mtxSignid,jdbcType=VARCHAR}, #{bcAddress,jdbcType=VARCHAR}, ",
        "#{mtxHash,jdbcType=VARCHAR}, #{signData,jdbcType=VARCHAR}, ",
        "#{txStatus,jdbcType=CHAR}, #{indexInTx,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCMtxSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @InsertProvider(type=BCMtxSignatureSqlProvider.class, method="insertSelective")
    int insertSelective(BCMtxSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCMtxSignatureSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MTX_SIGNID", property="mtxSignid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BC_ADDRESS", property="bcAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="MTX_HASH", property="mtxHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_DATA", property="signData", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_STATUS", property="txStatus", jdbcType=JdbcType.CHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCMtxSignature> selectByExample(BCMtxSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Select({
        "select",
        "MTX_SIGNID, BC_ADDRESS, MTX_HASH, SIGN_DATA, TX_STATUS, INDEX_IN_TX, CREATE_TIME, ",
        "UPDATE_TIME",
        "from BC_MTX_SIGNATURE",
        "where MTX_SIGNID = #{mtxSignid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MTX_SIGNID", property="mtxSignid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BC_ADDRESS", property="bcAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="MTX_HASH", property="mtxHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_DATA", property="signData", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_STATUS", property="txStatus", jdbcType=JdbcType.CHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCMtxSignature selectByPrimaryKey(BCMtxSignatureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCMtxSignatureSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCMtxSignature record, @Param("example") BCMtxSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCMtxSignatureSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCMtxSignature record, @Param("example") BCMtxSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCMtxSignatureSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCMtxSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Update({
        "update BC_MTX_SIGNATURE",
        "set BC_ADDRESS = #{bcAddress,jdbcType=VARCHAR},",
          "MTX_HASH = #{mtxHash,jdbcType=VARCHAR},",
          "SIGN_DATA = #{signData,jdbcType=VARCHAR},",
          "TX_STATUS = #{txStatus,jdbcType=CHAR},",
          "INDEX_IN_TX = #{indexInTx,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where MTX_SIGNID = #{mtxSignid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCMtxSignature record);
}