package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxOutput;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxOutputExample;
import org.brewchain.backend.ordbgens.bc.entity.BCMtxOutputKey;

public interface BCMtxOutputMapper extends StaticTableDaoSupport<BCMtxOutput, BCMtxOutputExample, BCMtxOutputKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCMtxOutputSqlProvider.class, method="countByExample")
    int countByExample(BCMtxOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @DeleteProvider(type=BCMtxOutputSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCMtxOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Delete({
        "delete from BC_MTX_OUTPUT",
        "where MTX_OUTPUTID = #{mtxOutputid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCMtxOutputKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Insert({
        "insert into BC_MTX_OUTPUT (MTX_OUTPUTID, BC_ADDRESS, ",
        "MTX_HASH, AMOUNT, ",
        "TOKEN_SYMBOL, TX_STATUS, ",
        "INDEX_IN_TX, CREATE_TIME, ",
        "UPDATE_TIME)",
        "values (#{mtxOutputid,jdbcType=VARCHAR}, #{bcAddress,jdbcType=VARCHAR}, ",
        "#{mtxHash,jdbcType=VARCHAR}, #{amount,jdbcType=DECIMAL}, ",
        "#{tokenSymbol,jdbcType=VARCHAR}, #{txStatus,jdbcType=CHAR}, ",
        "#{indexInTx,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCMtxOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @InsertProvider(type=BCMtxOutputSqlProvider.class, method="insertSelective")
    int insertSelective(BCMtxOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @SelectProvider(type=BCMtxOutputSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MTX_OUTPUTID", property="mtxOutputid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BC_ADDRESS", property="bcAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="MTX_HASH", property="mtxHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="TOKEN_SYMBOL", property="tokenSymbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_STATUS", property="txStatus", jdbcType=JdbcType.CHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCMtxOutput> selectByExample(BCMtxOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Select({
        "select",
        "MTX_OUTPUTID, BC_ADDRESS, MTX_HASH, AMOUNT, TOKEN_SYMBOL, TX_STATUS, INDEX_IN_TX, ",
        "CREATE_TIME, UPDATE_TIME",
        "from BC_MTX_OUTPUT",
        "where MTX_OUTPUTID = #{mtxOutputid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MTX_OUTPUTID", property="mtxOutputid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BC_ADDRESS", property="bcAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="MTX_HASH", property="mtxHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="TOKEN_SYMBOL", property="tokenSymbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="TX_STATUS", property="txStatus", jdbcType=JdbcType.CHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCMtxOutput selectByPrimaryKey(BCMtxOutputKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCMtxOutputSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCMtxOutput record, @Param("example") BCMtxOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCMtxOutputSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCMtxOutput record, @Param("example") BCMtxOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @UpdateProvider(type=BCMtxOutputSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCMtxOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Update({
        "update BC_MTX_OUTPUT",
        "set BC_ADDRESS = #{bcAddress,jdbcType=VARCHAR},",
          "MTX_HASH = #{mtxHash,jdbcType=VARCHAR},",
          "AMOUNT = #{amount,jdbcType=DECIMAL},",
          "TOKEN_SYMBOL = #{tokenSymbol,jdbcType=VARCHAR},",
          "TX_STATUS = #{txStatus,jdbcType=CHAR},",
          "INDEX_IN_TX = #{indexInTx,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where MTX_OUTPUTID = #{mtxOutputid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCMtxOutput record);
}