package org.brewchain.backend.ordbgens.bc.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.backend.ordbgens.bc.entity.BCMutilTransacton;
import org.brewchain.backend.ordbgens.bc.entity.BCMutilTransactonExample.Criteria;
import org.brewchain.backend.ordbgens.bc.entity.BCMutilTransactonExample.Criterion;
import org.brewchain.backend.ordbgens.bc.entity.BCMutilTransactonExample;

public class BCMutilTransactonSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String countByExample(BCMutilTransactonExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("BC_MUTIL_TRANSACTON");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String deleteByExample(BCMutilTransactonExample example) {
        BEGIN();
        DELETE_FROM("BC_MUTIL_TRANSACTON");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String insertSelective(BCMutilTransacton record) {
        BEGIN();
        INSERT_INTO("BC_MUTIL_TRANSACTON");
        
        if (record.getTxHash() != null) {
            VALUES("TX_HASH", "#{txHash,jdbcType=VARCHAR}");
        }
        
        if (record.getBversion() != null) {
            VALUES("BVERSION", "#{bversion,jdbcType=VARCHAR}");
        }
        
        if (record.getHashMerkleRoot() != null) {
            VALUES("HASH_MERKLE_ROOT", "#{hashMerkleRoot,jdbcType=VARCHAR}");
        }
        
        if (record.getBlockHeight() != null) {
            VALUES("BLOCK_HEIGHT", "#{blockHeight,jdbcType=DECIMAL}");
        }
        
        if (record.getAddressInCount() != null) {
            VALUES("ADDRESS_IN_COUNT", "#{addressInCount,jdbcType=INTEGER}");
        }
        
        if (record.getAddressOutCount() != null) {
            VALUES("ADDRESS_OUT_COUNT", "#{addressOutCount,jdbcType=INTEGER}");
        }
        
        if (record.getPropCount() != null) {
            VALUES("PROP_COUNT", "#{propCount,jdbcType=INTEGER}");
        }
        
        if (record.getTxStatus() != null) {
            VALUES("TX_STATUS", "#{txStatus,jdbcType=CHAR}");
        }
        
        if (record.getIndexInBlock() != null) {
            VALUES("INDEX_IN_BLOCK", "#{indexInBlock,jdbcType=INTEGER}");
        }
        
        if (record.getResultsHex() != null) {
            VALUES("RESULTS_HEX", "#{resultsHex,jdbcType=VARCHAR}");
        }
        
        if (record.getData() != null) {
            VALUES("DATA", "#{data,jdbcType=VARCHAR}");
        }
        
        if (record.getExtraData() != null) {
            VALUES("EXTRA_DATA", "#{extraData,jdbcType=VARCHAR}");
        }
        
        if (record.getTxTimestamp() != null) {
            VALUES("TX_TIMESTAMP", "#{txTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getTxType() != null) {
            VALUES("TX_TYPE", "#{txType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String selectByExample(BCMutilTransactonExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("TX_HASH");
        } else {
            SELECT("TX_HASH");
        }
        SELECT("BVERSION");
        SELECT("HASH_MERKLE_ROOT");
        SELECT("BLOCK_HEIGHT");
        SELECT("ADDRESS_IN_COUNT");
        SELECT("ADDRESS_OUT_COUNT");
        SELECT("PROP_COUNT");
        SELECT("TX_STATUS");
        SELECT("INDEX_IN_BLOCK");
        SELECT("RESULTS_HEX");
        SELECT("DATA");
        SELECT("EXTRA_DATA");
        SELECT("TX_TIMESTAMP");
        SELECT("TX_TYPE");
        SELECT("CREATE_TIME");
        SELECT("UPDATE_TIME");
        FROM("BC_MUTIL_TRANSACTON");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("BC_MUTIL_TRANSACTON");				applyWhere(example, false);
		}
        if(example != null){
            String sql = SQL();

            if(example.getGroupByClause()!=null&&example.getGroupByClause().trim().length()>0)  sql=sql.concat("group by ").concat(example.getGroupByClause());
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= sql.concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return sql+"  FOR UPDATE " ;  }
                
		return sql;}

                return SQL();
            }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BCMutilTransacton record = (BCMutilTransacton) parameter.get("record");
        BCMutilTransactonExample example = (BCMutilTransactonExample) parameter.get("example");
        
        BEGIN();
        UPDATE("BC_MUTIL_TRANSACTON");
        
        if (record.getTxHash() != null) {
            SET("TX_HASH = #{record.txHash,jdbcType=VARCHAR}");
        }
        
        if (record.getBversion() != null) {
            SET("BVERSION = #{record.bversion,jdbcType=VARCHAR}");
        }
        
        if (record.getHashMerkleRoot() != null) {
            SET("HASH_MERKLE_ROOT = #{record.hashMerkleRoot,jdbcType=VARCHAR}");
        }
        
        if (record.getBlockHeight() != null) {
            SET("BLOCK_HEIGHT = #{record.blockHeight,jdbcType=DECIMAL}");
        }
        
        if (record.getAddressInCount() != null) {
            SET("ADDRESS_IN_COUNT = #{record.addressInCount,jdbcType=INTEGER}");
        }
        
        if (record.getAddressOutCount() != null) {
            SET("ADDRESS_OUT_COUNT = #{record.addressOutCount,jdbcType=INTEGER}");
        }
        
        if (record.getPropCount() != null) {
            SET("PROP_COUNT = #{record.propCount,jdbcType=INTEGER}");
        }
        
        if (record.getTxStatus() != null) {
            SET("TX_STATUS = #{record.txStatus,jdbcType=CHAR}");
        }
        
        if (record.getIndexInBlock() != null) {
            SET("INDEX_IN_BLOCK = #{record.indexInBlock,jdbcType=INTEGER}");
        }
        
        if (record.getResultsHex() != null) {
            SET("RESULTS_HEX = #{record.resultsHex,jdbcType=VARCHAR}");
        }
        
        if (record.getData() != null) {
            SET("DATA = #{record.data,jdbcType=VARCHAR}");
        }
        
        if (record.getExtraData() != null) {
            SET("EXTRA_DATA = #{record.extraData,jdbcType=VARCHAR}");
        }
        
        if (record.getTxTimestamp() != null) {
            SET("TX_TIMESTAMP = #{record.txTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getTxType() != null) {
            SET("TX_TYPE = #{record.txType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("BC_MUTIL_TRANSACTON");
        
        SET("TX_HASH = #{record.txHash,jdbcType=VARCHAR}");
        SET("BVERSION = #{record.bversion,jdbcType=VARCHAR}");
        SET("HASH_MERKLE_ROOT = #{record.hashMerkleRoot,jdbcType=VARCHAR}");
        SET("BLOCK_HEIGHT = #{record.blockHeight,jdbcType=DECIMAL}");
        SET("ADDRESS_IN_COUNT = #{record.addressInCount,jdbcType=INTEGER}");
        SET("ADDRESS_OUT_COUNT = #{record.addressOutCount,jdbcType=INTEGER}");
        SET("PROP_COUNT = #{record.propCount,jdbcType=INTEGER}");
        SET("TX_STATUS = #{record.txStatus,jdbcType=CHAR}");
        SET("INDEX_IN_BLOCK = #{record.indexInBlock,jdbcType=INTEGER}");
        SET("RESULTS_HEX = #{record.resultsHex,jdbcType=VARCHAR}");
        SET("DATA = #{record.data,jdbcType=VARCHAR}");
        SET("EXTRA_DATA = #{record.extraData,jdbcType=VARCHAR}");
        SET("TX_TIMESTAMP = #{record.txTimestamp,jdbcType=DECIMAL}");
        SET("TX_TYPE = #{record.txType,jdbcType=INTEGER}");
        SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("UPDATE_TIME = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        BCMutilTransactonExample example = (BCMutilTransactonExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String updateByPrimaryKeySelective(BCMutilTransacton record) {
        BEGIN();
        UPDATE("BC_MUTIL_TRANSACTON");
        
        if (record.getBversion() != null) {
            SET("BVERSION = #{bversion,jdbcType=VARCHAR}");
        }
        
        if (record.getHashMerkleRoot() != null) {
            SET("HASH_MERKLE_ROOT = #{hashMerkleRoot,jdbcType=VARCHAR}");
        }
        
        if (record.getBlockHeight() != null) {
            SET("BLOCK_HEIGHT = #{blockHeight,jdbcType=DECIMAL}");
        }
        
        if (record.getAddressInCount() != null) {
            SET("ADDRESS_IN_COUNT = #{addressInCount,jdbcType=INTEGER}");
        }
        
        if (record.getAddressOutCount() != null) {
            SET("ADDRESS_OUT_COUNT = #{addressOutCount,jdbcType=INTEGER}");
        }
        
        if (record.getPropCount() != null) {
            SET("PROP_COUNT = #{propCount,jdbcType=INTEGER}");
        }
        
        if (record.getTxStatus() != null) {
            SET("TX_STATUS = #{txStatus,jdbcType=CHAR}");
        }
        
        if (record.getIndexInBlock() != null) {
            SET("INDEX_IN_BLOCK = #{indexInBlock,jdbcType=INTEGER}");
        }
        
        if (record.getResultsHex() != null) {
            SET("RESULTS_HEX = #{resultsHex,jdbcType=VARCHAR}");
        }
        
        if (record.getData() != null) {
            SET("DATA = #{data,jdbcType=VARCHAR}");
        }
        
        if (record.getExtraData() != null) {
            SET("EXTRA_DATA = #{extraData,jdbcType=VARCHAR}");
        }
        
        if (record.getTxTimestamp() != null) {
            SET("TX_TIMESTAMP = #{txTimestamp,jdbcType=DECIMAL}");
        }
        
        if (record.getTxType() != null) {
            SET("TX_TYPE = #{txType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("TX_HASH = #{txHash,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MUTIL_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    protected void applyWhere(BCMutilTransactonExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}