package org.brewchain.backend.ordbgens.bc.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.backend.ordbgens.bc.entity.BCTransactonAddress;
import org.brewchain.backend.ordbgens.bc.entity.BCTransactonAddressExample;
import org.brewchain.backend.ordbgens.bc.entity.BCTransactonAddressKey;

public interface BCTransactonAddressMapper extends StaticTableDaoSupport<BCTransactonAddress, BCTransactonAddressExample, BCTransactonAddressKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCTransactonAddressSqlProvider.class, method="countByExample")
    int countByExample(BCTransactonAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @DeleteProvider(type=BCTransactonAddressSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCTransactonAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Delete({
        "delete from BC_TRANSACTON_ADDRESS",
        "where TXID = #{txid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BCTransactonAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Insert({
        "insert into BC_TRANSACTON_ADDRESS (TXID, LOG_UUID, ",
        "ADDRESS, BVERSION, ",
        "PREV_TXID, INDEX_IN_TX, ",
        "ADDR_TYPE, NEXT_SCRIPT_ID, ",
        "SVALUE, FEE, TAX, ",
        "EXT_COMMENTS, CREATE_TIME, ",
        "UPDATE_TIME)",
        "values (#{txid,jdbcType=VARCHAR}, #{logUuid,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{bversion,jdbcType=VARCHAR}, ",
        "#{prevTxid,jdbcType=VARCHAR}, #{indexInTx,jdbcType=INTEGER}, ",
        "#{addrType,jdbcType=CHAR}, #{nextScriptId,jdbcType=VARCHAR}, ",
        "#{svalue,jdbcType=DECIMAL}, #{fee,jdbcType=DECIMAL}, #{tax,jdbcType=DECIMAL}, ",
        "#{extComments,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BCTransactonAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @InsertProvider(type=BCTransactonAddressSqlProvider.class, method="insertSelective")
    int insertSelective(BCTransactonAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @SelectProvider(type=BCTransactonAddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="TXID", property="txid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_TXID", property="prevTxid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="ADDR_TYPE", property="addrType", jdbcType=JdbcType.CHAR),
        @Result(column="NEXT_SCRIPT_ID", property="nextScriptId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SVALUE", property="svalue", jdbcType=JdbcType.DECIMAL),
        @Result(column="FEE", property="fee", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX", property="tax", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXT_COMMENTS", property="extComments", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BCTransactonAddress> selectByExample(BCTransactonAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Select({
        "select",
        "TXID, LOG_UUID, ADDRESS, BVERSION, PREV_TXID, INDEX_IN_TX, ADDR_TYPE, NEXT_SCRIPT_ID, ",
        "SVALUE, FEE, TAX, EXT_COMMENTS, CREATE_TIME, UPDATE_TIME",
        "from BC_TRANSACTON_ADDRESS",
        "where TXID = #{txid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="TXID", property="txid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="LOG_UUID", property="logUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="BVERSION", property="bversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREV_TXID", property="prevTxid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INDEX_IN_TX", property="indexInTx", jdbcType=JdbcType.INTEGER),
        @Result(column="ADDR_TYPE", property="addrType", jdbcType=JdbcType.CHAR),
        @Result(column="NEXT_SCRIPT_ID", property="nextScriptId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SVALUE", property="svalue", jdbcType=JdbcType.DECIMAL),
        @Result(column="FEE", property="fee", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX", property="tax", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXT_COMMENTS", property="extComments", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BCTransactonAddress selectByPrimaryKey(BCTransactonAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCTransactonAddressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCTransactonAddress record, @Param("example") BCTransactonAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCTransactonAddressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCTransactonAddress record, @Param("example") BCTransactonAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @UpdateProvider(type=BCTransactonAddressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCTransactonAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Update({
        "update BC_TRANSACTON_ADDRESS",
        "set LOG_UUID = #{logUuid,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "BVERSION = #{bversion,jdbcType=VARCHAR},",
          "PREV_TXID = #{prevTxid,jdbcType=VARCHAR},",
          "INDEX_IN_TX = #{indexInTx,jdbcType=INTEGER},",
          "ADDR_TYPE = #{addrType,jdbcType=CHAR},",
          "NEXT_SCRIPT_ID = #{nextScriptId,jdbcType=VARCHAR},",
          "SVALUE = #{svalue,jdbcType=DECIMAL},",
          "FEE = #{fee,jdbcType=DECIMAL},",
          "TAX = #{tax,jdbcType=DECIMAL},",
          "EXT_COMMENTS = #{extComments,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where TXID = #{txid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BCTransactonAddress record);
}