package org.brewchain.backend.ordbgens.bc.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class BCAccountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_ADDRESS
     *
     * @return the value of BC_ACCOUNT.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActAddress() {
        return actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_ADDRESS
     *
     * @param actAddress the value for BC_ACCOUNT.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActAddress(String actAddress) {
        this.actAddress = actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCAccountKey other = (BCAccountKey) that;
        return (this.getActAddress() == null ? other.getActAddress() == null : this.getActAddress().equals(other.getActAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActAddress() == null) ? 0 : getActAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actAddress=").append(actAddress);
        sb.append("]");
        return sb.toString();
    }
}