package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_ACCOUNT")
@AllArgsConstructor
@NoArgsConstructor
public class BCAccount extends BCAccountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Integer actNonce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_ACCEPT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actAcceptMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_ACCEPT_LIMIT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actAcceptLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.STORAGE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String storageHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.CODE_HASH_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String codeHashHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.CODE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String codeHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String dataHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.ACT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_NONCE
     *
     * @return the value of BC_ACCOUNT.ACT_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Integer getActNonce() {
        return actNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_NONCE
     *
     * @param actNonce the value for BC_ACCOUNT.ACT_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActNonce(Integer actNonce) {
        this.actNonce = actNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_BALANCE
     *
     * @return the value of BC_ACCOUNT.ACT_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActBalance() {
        return actBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_BALANCE
     *
     * @param actBalance the value for BC_ACCOUNT.ACT_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActBalance(BigDecimal actBalance) {
        this.actBalance = actBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_MAX
     *
     * @return the value of BC_ACCOUNT.ACT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActMax() {
        return actMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_MAX
     *
     * @param actMax the value for BC_ACCOUNT.ACT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActMax(BigDecimal actMax) {
        this.actMax = actMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_ACCEPT_MAX
     *
     * @return the value of BC_ACCOUNT.ACT_ACCEPT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActAcceptMax() {
        return actAcceptMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_ACCEPT_MAX
     *
     * @param actAcceptMax the value for BC_ACCOUNT.ACT_ACCEPT_MAX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActAcceptMax(BigDecimal actAcceptMax) {
        this.actAcceptMax = actAcceptMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_ACCEPT_LIMIT
     *
     * @return the value of BC_ACCOUNT.ACT_ACCEPT_LIMIT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActAcceptLimit() {
        return actAcceptLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_ACCEPT_LIMIT
     *
     * @param actAcceptLimit the value for BC_ACCOUNT.ACT_ACCEPT_LIMIT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActAcceptLimit(BigDecimal actAcceptLimit) {
        this.actAcceptLimit = actAcceptLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.STORAGE_HEX
     *
     * @return the value of BC_ACCOUNT.STORAGE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getStorageHex() {
        return storageHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.STORAGE_HEX
     *
     * @param storageHex the value for BC_ACCOUNT.STORAGE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setStorageHex(String storageHex) {
        this.storageHex = storageHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.CODE_HASH_HEX
     *
     * @return the value of BC_ACCOUNT.CODE_HASH_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getCodeHashHex() {
        return codeHashHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.CODE_HASH_HEX
     *
     * @param codeHashHex the value for BC_ACCOUNT.CODE_HASH_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setCodeHashHex(String codeHashHex) {
        this.codeHashHex = codeHashHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.CODE_HEX
     *
     * @return the value of BC_ACCOUNT.CODE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getCodeHex() {
        return codeHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.CODE_HEX
     *
     * @param codeHex the value for BC_ACCOUNT.CODE_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setCodeHex(String codeHex) {
        this.codeHex = codeHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.DATA_HEX
     *
     * @return the value of BC_ACCOUNT.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getDataHex() {
        return dataHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.DATA_HEX
     *
     * @param dataHex the value for BC_ACCOUNT.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setDataHex(String dataHex) {
        this.dataHex = dataHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.ACT_STATUS
     *
     * @return the value of BC_ACCOUNT.ACT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActStatus() {
        return actStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.ACT_STATUS
     *
     * @param actStatus the value for BC_ACCOUNT.ACT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActStatus(String actStatus) {
        this.actStatus = actStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.CREATE_TIME
     *
     * @return the value of BC_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.CREATE_TIME
     *
     * @param createTime the value for BC_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACCOUNT.UPDATE_TIME
     *
     * @return the value of BC_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACCOUNT.UPDATE_TIME
     *
     * @param updateTime the value for BC_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCAccount other = (BCAccount) that;
        return (this.getActAddress() == null ? other.getActAddress() == null : this.getActAddress().equals(other.getActAddress()))
            && (this.getActNonce() == null ? other.getActNonce() == null : this.getActNonce().equals(other.getActNonce()))
            && (this.getActBalance() == null ? other.getActBalance() == null : this.getActBalance().equals(other.getActBalance()))
            && (this.getActMax() == null ? other.getActMax() == null : this.getActMax().equals(other.getActMax()))
            && (this.getActAcceptMax() == null ? other.getActAcceptMax() == null : this.getActAcceptMax().equals(other.getActAcceptMax()))
            && (this.getActAcceptLimit() == null ? other.getActAcceptLimit() == null : this.getActAcceptLimit().equals(other.getActAcceptLimit()))
            && (this.getStorageHex() == null ? other.getStorageHex() == null : this.getStorageHex().equals(other.getStorageHex()))
            && (this.getCodeHashHex() == null ? other.getCodeHashHex() == null : this.getCodeHashHex().equals(other.getCodeHashHex()))
            && (this.getCodeHex() == null ? other.getCodeHex() == null : this.getCodeHex().equals(other.getCodeHex()))
            && (this.getDataHex() == null ? other.getDataHex() == null : this.getDataHex().equals(other.getDataHex()))
            && (this.getActStatus() == null ? other.getActStatus() == null : this.getActStatus().equals(other.getActStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActAddress() == null) ? 0 : getActAddress().hashCode());
        result = prime * result + ((getActNonce() == null) ? 0 : getActNonce().hashCode());
        result = prime * result + ((getActBalance() == null) ? 0 : getActBalance().hashCode());
        result = prime * result + ((getActMax() == null) ? 0 : getActMax().hashCode());
        result = prime * result + ((getActAcceptMax() == null) ? 0 : getActAcceptMax().hashCode());
        result = prime * result + ((getActAcceptLimit() == null) ? 0 : getActAcceptLimit().hashCode());
        result = prime * result + ((getStorageHex() == null) ? 0 : getStorageHex().hashCode());
        result = prime * result + ((getCodeHashHex() == null) ? 0 : getCodeHashHex().hashCode());
        result = prime * result + ((getCodeHex() == null) ? 0 : getCodeHex().hashCode());
        result = prime * result + ((getDataHex() == null) ? 0 : getDataHex().hashCode());
        result = prime * result + ((getActStatus() == null) ? 0 : getActStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACCOUNT
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actNonce=").append(actNonce);
        sb.append(", actBalance=").append(actBalance);
        sb.append(", actMax=").append(actMax);
        sb.append(", actAcceptMax=").append(actAcceptMax);
        sb.append(", actAcceptLimit=").append(actAcceptLimit);
        sb.append(", storageHex=").append(storageHex);
        sb.append(", codeHashHex=").append(codeHashHex);
        sb.append(", codeHex=").append(codeHex);
        sb.append(", dataHex=").append(dataHex);
        sb.append(", actStatus=").append(actStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}