package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_ACT_CRYPTO_VALUE")
@AllArgsConstructor
@NoArgsConstructor
public class BCActCryptoValue extends BCActCryptoValueKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_HASH
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNER
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_NAME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_CODE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Integer actvNonce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_TIMESTAMP
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNERTIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvOwnertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_INDEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_TOTAL
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String dataHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.ACTV_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_CRYPTO_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_HASH
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_HASH
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvHash() {
        return actvHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_HASH
     *
     * @param actvHash the value for BC_ACT_CRYPTO_VALUE.ACTV_HASH
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvHash(String actvHash) {
        this.actvHash = actvHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACT_ADDRESS
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActAddress() {
        return actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACT_ADDRESS
     *
     * @param actAddress the value for BC_ACT_CRYPTO_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActAddress(String actAddress) {
        this.actAddress = actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNER
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_OWNER
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvOwner() {
        return actvOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNER
     *
     * @param actvOwner the value for BC_ACT_CRYPTO_VALUE.ACTV_OWNER
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvOwner(String actvOwner) {
        this.actvOwner = actvOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_NAME
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_NAME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvName() {
        return actvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_NAME
     *
     * @param actvName the value for BC_ACT_CRYPTO_VALUE.ACTV_NAME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvName(String actvName) {
        this.actvName = actvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_CODE
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_CODE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvCode() {
        return actvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_CODE
     *
     * @param actvCode the value for BC_ACT_CRYPTO_VALUE.ACTV_CODE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvCode(String actvCode) {
        this.actvCode = actvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_NONCE
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Integer getActvNonce() {
        return actvNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_NONCE
     *
     * @param actvNonce the value for BC_ACT_CRYPTO_VALUE.ACTV_NONCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvNonce(Integer actvNonce) {
        this.actvNonce = actvNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_TIMESTAMP
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_TIMESTAMP
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvTimestamp() {
        return actvTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_TIMESTAMP
     *
     * @param actvTimestamp the value for BC_ACT_CRYPTO_VALUE.ACTV_TIMESTAMP
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvTimestamp(BigDecimal actvTimestamp) {
        this.actvTimestamp = actvTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNERTIME
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_OWNERTIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvOwnertime() {
        return actvOwnertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_OWNERTIME
     *
     * @param actvOwnertime the value for BC_ACT_CRYPTO_VALUE.ACTV_OWNERTIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvOwnertime(BigDecimal actvOwnertime) {
        this.actvOwnertime = actvOwnertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_INDEX
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_INDEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvIndex() {
        return actvIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_INDEX
     *
     * @param actvIndex the value for BC_ACT_CRYPTO_VALUE.ACTV_INDEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvIndex(BigDecimal actvIndex) {
        this.actvIndex = actvIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_TOTAL
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_TOTAL
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvTotal() {
        return actvTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_TOTAL
     *
     * @param actvTotal the value for BC_ACT_CRYPTO_VALUE.ACTV_TOTAL
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvTotal(BigDecimal actvTotal) {
        this.actvTotal = actvTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.DATA_HEX
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getDataHex() {
        return dataHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.DATA_HEX
     *
     * @param dataHex the value for BC_ACT_CRYPTO_VALUE.DATA_HEX
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setDataHex(String dataHex) {
        this.dataHex = dataHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_STATUS
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.ACTV_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvStatus() {
        return actvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.ACTV_STATUS
     *
     * @param actvStatus the value for BC_ACT_CRYPTO_VALUE.ACTV_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvStatus(String actvStatus) {
        this.actvStatus = actvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.CREATE_TIME
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.CREATE_TIME
     *
     * @param createTime the value for BC_ACT_CRYPTO_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_CRYPTO_VALUE.UPDATE_TIME
     *
     * @return the value of BC_ACT_CRYPTO_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_CRYPTO_VALUE.UPDATE_TIME
     *
     * @param updateTime the value for BC_ACT_CRYPTO_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCActCryptoValue other = (BCActCryptoValue) that;
        return (this.getActvUid() == null ? other.getActvUid() == null : this.getActvUid().equals(other.getActvUid()))
            && (this.getActvHash() == null ? other.getActvHash() == null : this.getActvHash().equals(other.getActvHash()))
            && (this.getActAddress() == null ? other.getActAddress() == null : this.getActAddress().equals(other.getActAddress()))
            && (this.getActvOwner() == null ? other.getActvOwner() == null : this.getActvOwner().equals(other.getActvOwner()))
            && (this.getActvName() == null ? other.getActvName() == null : this.getActvName().equals(other.getActvName()))
            && (this.getActvCode() == null ? other.getActvCode() == null : this.getActvCode().equals(other.getActvCode()))
            && (this.getActvNonce() == null ? other.getActvNonce() == null : this.getActvNonce().equals(other.getActvNonce()))
            && (this.getActvTimestamp() == null ? other.getActvTimestamp() == null : this.getActvTimestamp().equals(other.getActvTimestamp()))
            && (this.getActvOwnertime() == null ? other.getActvOwnertime() == null : this.getActvOwnertime().equals(other.getActvOwnertime()))
            && (this.getActvIndex() == null ? other.getActvIndex() == null : this.getActvIndex().equals(other.getActvIndex()))
            && (this.getActvTotal() == null ? other.getActvTotal() == null : this.getActvTotal().equals(other.getActvTotal()))
            && (this.getDataHex() == null ? other.getDataHex() == null : this.getDataHex().equals(other.getDataHex()))
            && (this.getActvStatus() == null ? other.getActvStatus() == null : this.getActvStatus().equals(other.getActvStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActvUid() == null) ? 0 : getActvUid().hashCode());
        result = prime * result + ((getActvHash() == null) ? 0 : getActvHash().hashCode());
        result = prime * result + ((getActAddress() == null) ? 0 : getActAddress().hashCode());
        result = prime * result + ((getActvOwner() == null) ? 0 : getActvOwner().hashCode());
        result = prime * result + ((getActvName() == null) ? 0 : getActvName().hashCode());
        result = prime * result + ((getActvCode() == null) ? 0 : getActvCode().hashCode());
        result = prime * result + ((getActvNonce() == null) ? 0 : getActvNonce().hashCode());
        result = prime * result + ((getActvTimestamp() == null) ? 0 : getActvTimestamp().hashCode());
        result = prime * result + ((getActvOwnertime() == null) ? 0 : getActvOwnertime().hashCode());
        result = prime * result + ((getActvIndex() == null) ? 0 : getActvIndex().hashCode());
        result = prime * result + ((getActvTotal() == null) ? 0 : getActvTotal().hashCode());
        result = prime * result + ((getDataHex() == null) ? 0 : getDataHex().hashCode());
        result = prime * result + ((getActvStatus() == null) ? 0 : getActvStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actvHash=").append(actvHash);
        sb.append(", actAddress=").append(actAddress);
        sb.append(", actvOwner=").append(actvOwner);
        sb.append(", actvName=").append(actvName);
        sb.append(", actvCode=").append(actvCode);
        sb.append(", actvNonce=").append(actvNonce);
        sb.append(", actvTimestamp=").append(actvTimestamp);
        sb.append(", actvOwnertime=").append(actvOwnertime);
        sb.append(", actvIndex=").append(actvIndex);
        sb.append(", actvTotal=").append(actvTotal);
        sb.append(", dataHex=").append(dataHex);
        sb.append(", actvStatus=").append(actvStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}