package org.brewchain.backend.ordbgens.bc.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_ACT_ADDRESS")
@AllArgsConstructor
@NoArgsConstructor
public class BCActAddress extends BCActAddressKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_ADDRESS.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    private String actAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_ADDRESS.ACTA_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    private String actaStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_ADDRESS.ACT_ADDRESS
     *
     * @return the value of BC_ACT_ADDRESS.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String getActAddress() {
        return actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_ADDRESS.ACT_ADDRESS
     *
     * @param actAddress the value for BC_ACT_ADDRESS.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public void setActAddress(String actAddress) {
        this.actAddress = actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_ADDRESS.ACTA_STATUS
     *
     * @return the value of BC_ACT_ADDRESS.ACTA_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public String getActaStatus() {
        return actaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_ADDRESS.ACTA_STATUS
     *
     * @param actaStatus the value for BC_ACT_ADDRESS.ACTA_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public void setActaStatus(String actaStatus) {
        this.actaStatus = actaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_ADDRESS.CREATE_TIME
     *
     * @return the value of BC_ACT_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_ADDRESS.CREATE_TIME
     *
     * @param createTime the value for BC_ACT_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_ADDRESS.UPDATE_TIME
     *
     * @return the value of BC_ACT_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_ADDRESS.UPDATE_TIME
     *
     * @param updateTime the value for BC_ACT_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCActAddress other = (BCActAddress) that;
        return (this.getAddressUid() == null ? other.getAddressUid() == null : this.getAddressUid().equals(other.getAddressUid()))
            && (this.getActAddress() == null ? other.getActAddress() == null : this.getActAddress().equals(other.getActAddress()))
            && (this.getActaStatus() == null ? other.getActaStatus() == null : this.getActaStatus().equals(other.getActaStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddressUid() == null) ? 0 : getAddressUid().hashCode());
        result = prime * result + ((getActAddress() == null) ? 0 : getActAddress().hashCode());
        result = prime * result + ((getActaStatus() == null) ? 0 : getActaStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:27 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actAddress=").append(actAddress);
        sb.append(", actaStatus=").append(actaStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}