package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class BCActCryptoValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BCActCryptoValueExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActvUidIsNull() {
            addCriterion("ACTV_UID is null");
            return (Criteria) this;
        }

        public Criteria andActvUidIsNotNull() {
            addCriterion("ACTV_UID is not null");
            return (Criteria) this;
        }

        public Criteria andActvUidEqualTo(String value) {
            addCriterion("ACTV_UID =", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidNotEqualTo(String value) {
            addCriterion("ACTV_UID <>", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidGreaterThan(String value) {
            addCriterion("ACTV_UID >", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_UID >=", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidLessThan(String value) {
            addCriterion("ACTV_UID <", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidLessThanOrEqualTo(String value) {
            addCriterion("ACTV_UID <=", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidLike(String value) {
            addCriterion("ACTV_UID like", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidNotLike(String value) {
            addCriterion("ACTV_UID not like", value, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidIn(List<String> values) {
            addCriterion("ACTV_UID in", values, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidNotIn(List<String> values) {
            addCriterion("ACTV_UID not in", values, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidBetween(String value1, String value2) {
            addCriterion("ACTV_UID between", value1, value2, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvUidNotBetween(String value1, String value2) {
            addCriterion("ACTV_UID not between", value1, value2, "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvHashIsNull() {
            addCriterion("ACTV_HASH is null");
            return (Criteria) this;
        }

        public Criteria andActvHashIsNotNull() {
            addCriterion("ACTV_HASH is not null");
            return (Criteria) this;
        }

        public Criteria andActvHashEqualTo(String value) {
            addCriterion("ACTV_HASH =", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashNotEqualTo(String value) {
            addCriterion("ACTV_HASH <>", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashGreaterThan(String value) {
            addCriterion("ACTV_HASH >", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_HASH >=", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashLessThan(String value) {
            addCriterion("ACTV_HASH <", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashLessThanOrEqualTo(String value) {
            addCriterion("ACTV_HASH <=", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashLike(String value) {
            addCriterion("ACTV_HASH like", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashNotLike(String value) {
            addCriterion("ACTV_HASH not like", value, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashIn(List<String> values) {
            addCriterion("ACTV_HASH in", values, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashNotIn(List<String> values) {
            addCriterion("ACTV_HASH not in", values, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashBetween(String value1, String value2) {
            addCriterion("ACTV_HASH between", value1, value2, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActvHashNotBetween(String value1, String value2) {
            addCriterion("ACTV_HASH not between", value1, value2, "actvHash");
            return (Criteria) this;
        }

        public Criteria andActAddressIsNull() {
            addCriterion("ACT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andActAddressIsNotNull() {
            addCriterion("ACT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andActAddressEqualTo(String value) {
            addCriterion("ACT_ADDRESS =", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressNotEqualTo(String value) {
            addCriterion("ACT_ADDRESS <>", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressGreaterThan(String value) {
            addCriterion("ACT_ADDRESS >", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_ADDRESS >=", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressLessThan(String value) {
            addCriterion("ACT_ADDRESS <", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressLessThanOrEqualTo(String value) {
            addCriterion("ACT_ADDRESS <=", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressLike(String value) {
            addCriterion("ACT_ADDRESS like", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressNotLike(String value) {
            addCriterion("ACT_ADDRESS not like", value, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressIn(List<String> values) {
            addCriterion("ACT_ADDRESS in", values, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressNotIn(List<String> values) {
            addCriterion("ACT_ADDRESS not in", values, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressBetween(String value1, String value2) {
            addCriterion("ACT_ADDRESS between", value1, value2, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActAddressNotBetween(String value1, String value2) {
            addCriterion("ACT_ADDRESS not between", value1, value2, "actAddress");
            return (Criteria) this;
        }

        public Criteria andActvOwnerIsNull() {
            addCriterion("ACTV_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andActvOwnerIsNotNull() {
            addCriterion("ACTV_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andActvOwnerEqualTo(String value) {
            addCriterion("ACTV_OWNER =", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerNotEqualTo(String value) {
            addCriterion("ACTV_OWNER <>", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerGreaterThan(String value) {
            addCriterion("ACTV_OWNER >", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_OWNER >=", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerLessThan(String value) {
            addCriterion("ACTV_OWNER <", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerLessThanOrEqualTo(String value) {
            addCriterion("ACTV_OWNER <=", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerLike(String value) {
            addCriterion("ACTV_OWNER like", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerNotLike(String value) {
            addCriterion("ACTV_OWNER not like", value, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerIn(List<String> values) {
            addCriterion("ACTV_OWNER in", values, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerNotIn(List<String> values) {
            addCriterion("ACTV_OWNER not in", values, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerBetween(String value1, String value2) {
            addCriterion("ACTV_OWNER between", value1, value2, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvOwnerNotBetween(String value1, String value2) {
            addCriterion("ACTV_OWNER not between", value1, value2, "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvNameIsNull() {
            addCriterion("ACTV_NAME is null");
            return (Criteria) this;
        }

        public Criteria andActvNameIsNotNull() {
            addCriterion("ACTV_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andActvNameEqualTo(String value) {
            addCriterion("ACTV_NAME =", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameNotEqualTo(String value) {
            addCriterion("ACTV_NAME <>", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameGreaterThan(String value) {
            addCriterion("ACTV_NAME >", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_NAME >=", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameLessThan(String value) {
            addCriterion("ACTV_NAME <", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameLessThanOrEqualTo(String value) {
            addCriterion("ACTV_NAME <=", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameLike(String value) {
            addCriterion("ACTV_NAME like", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameNotLike(String value) {
            addCriterion("ACTV_NAME not like", value, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameIn(List<String> values) {
            addCriterion("ACTV_NAME in", values, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameNotIn(List<String> values) {
            addCriterion("ACTV_NAME not in", values, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameBetween(String value1, String value2) {
            addCriterion("ACTV_NAME between", value1, value2, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvNameNotBetween(String value1, String value2) {
            addCriterion("ACTV_NAME not between", value1, value2, "actvName");
            return (Criteria) this;
        }

        public Criteria andActvCodeIsNull() {
            addCriterion("ACTV_CODE is null");
            return (Criteria) this;
        }

        public Criteria andActvCodeIsNotNull() {
            addCriterion("ACTV_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andActvCodeEqualTo(String value) {
            addCriterion("ACTV_CODE =", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeNotEqualTo(String value) {
            addCriterion("ACTV_CODE <>", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeGreaterThan(String value) {
            addCriterion("ACTV_CODE >", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_CODE >=", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeLessThan(String value) {
            addCriterion("ACTV_CODE <", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeLessThanOrEqualTo(String value) {
            addCriterion("ACTV_CODE <=", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeLike(String value) {
            addCriterion("ACTV_CODE like", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeNotLike(String value) {
            addCriterion("ACTV_CODE not like", value, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeIn(List<String> values) {
            addCriterion("ACTV_CODE in", values, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeNotIn(List<String> values) {
            addCriterion("ACTV_CODE not in", values, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeBetween(String value1, String value2) {
            addCriterion("ACTV_CODE between", value1, value2, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvCodeNotBetween(String value1, String value2) {
            addCriterion("ACTV_CODE not between", value1, value2, "actvCode");
            return (Criteria) this;
        }

        public Criteria andActvNonceIsNull() {
            addCriterion("ACTV_NONCE is null");
            return (Criteria) this;
        }

        public Criteria andActvNonceIsNotNull() {
            addCriterion("ACTV_NONCE is not null");
            return (Criteria) this;
        }

        public Criteria andActvNonceEqualTo(Integer value) {
            addCriterion("ACTV_NONCE =", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceNotEqualTo(Integer value) {
            addCriterion("ACTV_NONCE <>", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceGreaterThan(Integer value) {
            addCriterion("ACTV_NONCE >", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTV_NONCE >=", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceLessThan(Integer value) {
            addCriterion("ACTV_NONCE <", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceLessThanOrEqualTo(Integer value) {
            addCriterion("ACTV_NONCE <=", value, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceIn(List<Integer> values) {
            addCriterion("ACTV_NONCE in", values, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceNotIn(List<Integer> values) {
            addCriterion("ACTV_NONCE not in", values, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceBetween(Integer value1, Integer value2) {
            addCriterion("ACTV_NONCE between", value1, value2, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvNonceNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTV_NONCE not between", value1, value2, "actvNonce");
            return (Criteria) this;
        }

        public Criteria andActvTimestampIsNull() {
            addCriterion("ACTV_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andActvTimestampIsNotNull() {
            addCriterion("ACTV_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andActvTimestampEqualTo(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP =", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampNotEqualTo(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP <>", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampGreaterThan(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP >", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP >=", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampLessThan(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP <", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_TIMESTAMP <=", value, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampIn(List<BigDecimal> values) {
            addCriterion("ACTV_TIMESTAMP in", values, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampNotIn(List<BigDecimal> values) {
            addCriterion("ACTV_TIMESTAMP not in", values, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_TIMESTAMP between", value1, value2, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvTimestampNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_TIMESTAMP not between", value1, value2, "actvTimestamp");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeIsNull() {
            addCriterion("ACTV_OWNERTIME is null");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeIsNotNull() {
            addCriterion("ACTV_OWNERTIME is not null");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeEqualTo(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME =", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeNotEqualTo(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME <>", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeGreaterThan(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME >", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME >=", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeLessThan(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME <", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_OWNERTIME <=", value, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeIn(List<BigDecimal> values) {
            addCriterion("ACTV_OWNERTIME in", values, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeNotIn(List<BigDecimal> values) {
            addCriterion("ACTV_OWNERTIME not in", values, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_OWNERTIME between", value1, value2, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvOwnertimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_OWNERTIME not between", value1, value2, "actvOwnertime");
            return (Criteria) this;
        }

        public Criteria andActvIndexIsNull() {
            addCriterion("ACTV_INDEX is null");
            return (Criteria) this;
        }

        public Criteria andActvIndexIsNotNull() {
            addCriterion("ACTV_INDEX is not null");
            return (Criteria) this;
        }

        public Criteria andActvIndexEqualTo(BigDecimal value) {
            addCriterion("ACTV_INDEX =", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexNotEqualTo(BigDecimal value) {
            addCriterion("ACTV_INDEX <>", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexGreaterThan(BigDecimal value) {
            addCriterion("ACTV_INDEX >", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_INDEX >=", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexLessThan(BigDecimal value) {
            addCriterion("ACTV_INDEX <", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_INDEX <=", value, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexIn(List<BigDecimal> values) {
            addCriterion("ACTV_INDEX in", values, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexNotIn(List<BigDecimal> values) {
            addCriterion("ACTV_INDEX not in", values, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_INDEX between", value1, value2, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvIndexNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_INDEX not between", value1, value2, "actvIndex");
            return (Criteria) this;
        }

        public Criteria andActvTotalIsNull() {
            addCriterion("ACTV_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andActvTotalIsNotNull() {
            addCriterion("ACTV_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andActvTotalEqualTo(BigDecimal value) {
            addCriterion("ACTV_TOTAL =", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalNotEqualTo(BigDecimal value) {
            addCriterion("ACTV_TOTAL <>", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalGreaterThan(BigDecimal value) {
            addCriterion("ACTV_TOTAL >", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_TOTAL >=", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalLessThan(BigDecimal value) {
            addCriterion("ACTV_TOTAL <", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTV_TOTAL <=", value, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalIn(List<BigDecimal> values) {
            addCriterion("ACTV_TOTAL in", values, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalNotIn(List<BigDecimal> values) {
            addCriterion("ACTV_TOTAL not in", values, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_TOTAL between", value1, value2, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andActvTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTV_TOTAL not between", value1, value2, "actvTotal");
            return (Criteria) this;
        }

        public Criteria andDataHexIsNull() {
            addCriterion("DATA_HEX is null");
            return (Criteria) this;
        }

        public Criteria andDataHexIsNotNull() {
            addCriterion("DATA_HEX is not null");
            return (Criteria) this;
        }

        public Criteria andDataHexEqualTo(String value) {
            addCriterion("DATA_HEX =", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexNotEqualTo(String value) {
            addCriterion("DATA_HEX <>", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexGreaterThan(String value) {
            addCriterion("DATA_HEX >", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_HEX >=", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexLessThan(String value) {
            addCriterion("DATA_HEX <", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexLessThanOrEqualTo(String value) {
            addCriterion("DATA_HEX <=", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexLike(String value) {
            addCriterion("DATA_HEX like", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexNotLike(String value) {
            addCriterion("DATA_HEX not like", value, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexIn(List<String> values) {
            addCriterion("DATA_HEX in", values, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexNotIn(List<String> values) {
            addCriterion("DATA_HEX not in", values, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexBetween(String value1, String value2) {
            addCriterion("DATA_HEX between", value1, value2, "dataHex");
            return (Criteria) this;
        }

        public Criteria andDataHexNotBetween(String value1, String value2) {
            addCriterion("DATA_HEX not between", value1, value2, "dataHex");
            return (Criteria) this;
        }

        public Criteria andActvStatusIsNull() {
            addCriterion("ACTV_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andActvStatusIsNotNull() {
            addCriterion("ACTV_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andActvStatusEqualTo(String value) {
            addCriterion("ACTV_STATUS =", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusNotEqualTo(String value) {
            addCriterion("ACTV_STATUS <>", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusGreaterThan(String value) {
            addCriterion("ACTV_STATUS >", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ACTV_STATUS >=", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusLessThan(String value) {
            addCriterion("ACTV_STATUS <", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusLessThanOrEqualTo(String value) {
            addCriterion("ACTV_STATUS <=", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusLike(String value) {
            addCriterion("ACTV_STATUS like", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusNotLike(String value) {
            addCriterion("ACTV_STATUS not like", value, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusIn(List<String> values) {
            addCriterion("ACTV_STATUS in", values, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusNotIn(List<String> values) {
            addCriterion("ACTV_STATUS not in", values, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusBetween(String value1, String value2) {
            addCriterion("ACTV_STATUS between", value1, value2, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andActvStatusNotBetween(String value1, String value2) {
            addCriterion("ACTV_STATUS not between", value1, value2, "actvStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andActvUidLikeInsensitive(String value) {
            addCriterion("upper(ACTV_UID) like", value.toUpperCase(), "actvUid");
            return (Criteria) this;
        }

        public Criteria andActvHashLikeInsensitive(String value) {
            addCriterion("upper(ACTV_HASH) like", value.toUpperCase(), "actvHash");
            return (Criteria) this;
        }

        public Criteria andActAddressLikeInsensitive(String value) {
            addCriterion("upper(ACT_ADDRESS) like", value.toUpperCase(), "actAddress");
            return (Criteria) this;
        }

        public Criteria andActvOwnerLikeInsensitive(String value) {
            addCriterion("upper(ACTV_OWNER) like", value.toUpperCase(), "actvOwner");
            return (Criteria) this;
        }

        public Criteria andActvNameLikeInsensitive(String value) {
            addCriterion("upper(ACTV_NAME) like", value.toUpperCase(), "actvName");
            return (Criteria) this;
        }

        public Criteria andActvCodeLikeInsensitive(String value) {
            addCriterion("upper(ACTV_CODE) like", value.toUpperCase(), "actvCode");
            return (Criteria) this;
        }

        public Criteria andDataHexLikeInsensitive(String value) {
            addCriterion("upper(DATA_HEX) like", value.toUpperCase(), "dataHex");
            return (Criteria) this;
        }

        public Criteria andActvStatusLikeInsensitive(String value) {
            addCriterion("upper(ACTV_STATUS) like", value.toUpperCase(), "actvStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 21 20:51:19 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ACT_CRYPTO_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}