package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_ACT_TOKEN_VALUE")
@AllArgsConstructor
@NoArgsConstructor
public class BCActTokenValue extends BCActTokenValueKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.ACTV_TOKEN
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String actvToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.ACTV_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.ACTV_LOCKED
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private BigDecimal actvLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.ACTT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private String acttStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_ACT_TOKEN_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.ACT_ADDRESS
     *
     * @return the value of BC_ACT_TOKEN_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActAddress() {
        return actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.ACT_ADDRESS
     *
     * @param actAddress the value for BC_ACT_TOKEN_VALUE.ACT_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActAddress(String actAddress) {
        this.actAddress = actAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.ACTV_TOKEN
     *
     * @return the value of BC_ACT_TOKEN_VALUE.ACTV_TOKEN
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActvToken() {
        return actvToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.ACTV_TOKEN
     *
     * @param actvToken the value for BC_ACT_TOKEN_VALUE.ACTV_TOKEN
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvToken(String actvToken) {
        this.actvToken = actvToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.ACTV_BALANCE
     *
     * @return the value of BC_ACT_TOKEN_VALUE.ACTV_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvBalance() {
        return actvBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.ACTV_BALANCE
     *
     * @param actvBalance the value for BC_ACT_TOKEN_VALUE.ACTV_BALANCE
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvBalance(BigDecimal actvBalance) {
        this.actvBalance = actvBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.ACTV_LOCKED
     *
     * @return the value of BC_ACT_TOKEN_VALUE.ACTV_LOCKED
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public BigDecimal getActvLocked() {
        return actvLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.ACTV_LOCKED
     *
     * @param actvLocked the value for BC_ACT_TOKEN_VALUE.ACTV_LOCKED
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActvLocked(BigDecimal actvLocked) {
        this.actvLocked = actvLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.ACTT_STATUS
     *
     * @return the value of BC_ACT_TOKEN_VALUE.ACTT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public String getActtStatus() {
        return acttStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.ACTT_STATUS
     *
     * @param acttStatus the value for BC_ACT_TOKEN_VALUE.ACTT_STATUS
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setActtStatus(String acttStatus) {
        this.acttStatus = acttStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.CREATE_TIME
     *
     * @return the value of BC_ACT_TOKEN_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.CREATE_TIME
     *
     * @param createTime the value for BC_ACT_TOKEN_VALUE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_ACT_TOKEN_VALUE.UPDATE_TIME
     *
     * @return the value of BC_ACT_TOKEN_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_ACT_TOKEN_VALUE.UPDATE_TIME
     *
     * @param updateTime the value for BC_ACT_TOKEN_VALUE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:51:19 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCActTokenValue other = (BCActTokenValue) that;
        return (this.getActvTokenId() == null ? other.getActvTokenId() == null : this.getActvTokenId().equals(other.getActvTokenId()))
            && (this.getActAddress() == null ? other.getActAddress() == null : this.getActAddress().equals(other.getActAddress()))
            && (this.getActvToken() == null ? other.getActvToken() == null : this.getActvToken().equals(other.getActvToken()))
            && (this.getActvBalance() == null ? other.getActvBalance() == null : this.getActvBalance().equals(other.getActvBalance()))
            && (this.getActvLocked() == null ? other.getActvLocked() == null : this.getActvLocked().equals(other.getActvLocked()))
            && (this.getActtStatus() == null ? other.getActtStatus() == null : this.getActtStatus().equals(other.getActtStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActvTokenId() == null) ? 0 : getActvTokenId().hashCode());
        result = prime * result + ((getActAddress() == null) ? 0 : getActAddress().hashCode());
        result = prime * result + ((getActvToken() == null) ? 0 : getActvToken().hashCode());
        result = prime * result + ((getActvBalance() == null) ? 0 : getActvBalance().hashCode());
        result = prime * result + ((getActvLocked() == null) ? 0 : getActvLocked().hashCode());
        result = prime * result + ((getActtStatus() == null) ? 0 : getActtStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ACT_TOKEN_VALUE
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actAddress=").append(actAddress);
        sb.append(", actvToken=").append(actvToken);
        sb.append(", actvBalance=").append(actvBalance);
        sb.append(", actvLocked=").append(actvLocked);
        sb.append(", acttStatus=").append(acttStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}