package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class BCAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public BCAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTxidIsNull() {
            addCriterion("TXID is null");
            return (Criteria) this;
        }

        public Criteria andTxidIsNotNull() {
            addCriterion("TXID is not null");
            return (Criteria) this;
        }

        public Criteria andTxidEqualTo(String value) {
            addCriterion("TXID =", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotEqualTo(String value) {
            addCriterion("TXID <>", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidGreaterThan(String value) {
            addCriterion("TXID >", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidGreaterThanOrEqualTo(String value) {
            addCriterion("TXID >=", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLessThan(String value) {
            addCriterion("TXID <", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLessThanOrEqualTo(String value) {
            addCriterion("TXID <=", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLike(String value) {
            addCriterion("TXID like", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotLike(String value) {
            addCriterion("TXID not like", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidIn(List<String> values) {
            addCriterion("TXID in", values, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotIn(List<String> values) {
            addCriterion("TXID not in", values, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidBetween(String value1, String value2) {
            addCriterion("TXID between", value1, value2, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotBetween(String value1, String value2) {
            addCriterion("TXID not between", value1, value2, "txid");
            return (Criteria) this;
        }

        public Criteria andLogUuidIsNull() {
            addCriterion("LOG_UUID is null");
            return (Criteria) this;
        }

        public Criteria andLogUuidIsNotNull() {
            addCriterion("LOG_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andLogUuidEqualTo(String value) {
            addCriterion("LOG_UUID =", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotEqualTo(String value) {
            addCriterion("LOG_UUID <>", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThan(String value) {
            addCriterion("LOG_UUID >", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_UUID >=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThan(String value) {
            addCriterion("LOG_UUID <", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThanOrEqualTo(String value) {
            addCriterion("LOG_UUID <=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLike(String value) {
            addCriterion("LOG_UUID like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotLike(String value) {
            addCriterion("LOG_UUID not like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidIn(List<String> values) {
            addCriterion("LOG_UUID in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotIn(List<String> values) {
            addCriterion("LOG_UUID not in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidBetween(String value1, String value2) {
            addCriterion("LOG_UUID between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotBetween(String value1, String value2) {
            addCriterion("LOG_UUID not between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andBversionIsNull() {
            addCriterion("BVERSION is null");
            return (Criteria) this;
        }

        public Criteria andBversionIsNotNull() {
            addCriterion("BVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andBversionEqualTo(String value) {
            addCriterion("BVERSION =", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotEqualTo(String value) {
            addCriterion("BVERSION <>", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionGreaterThan(String value) {
            addCriterion("BVERSION >", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionGreaterThanOrEqualTo(String value) {
            addCriterion("BVERSION >=", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLessThan(String value) {
            addCriterion("BVERSION <", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLessThanOrEqualTo(String value) {
            addCriterion("BVERSION <=", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLike(String value) {
            addCriterion("BVERSION like", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotLike(String value) {
            addCriterion("BVERSION not like", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionIn(List<String> values) {
            addCriterion("BVERSION in", values, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotIn(List<String> values) {
            addCriterion("BVERSION not in", values, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionBetween(String value1, String value2) {
            addCriterion("BVERSION between", value1, value2, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotBetween(String value1, String value2) {
            addCriterion("BVERSION not between", value1, value2, "bversion");
            return (Criteria) this;
        }

        public Criteria andPrevTxidIsNull() {
            addCriterion("PREV_TXID is null");
            return (Criteria) this;
        }

        public Criteria andPrevTxidIsNotNull() {
            addCriterion("PREV_TXID is not null");
            return (Criteria) this;
        }

        public Criteria andPrevTxidEqualTo(String value) {
            addCriterion("PREV_TXID =", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidNotEqualTo(String value) {
            addCriterion("PREV_TXID <>", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidGreaterThan(String value) {
            addCriterion("PREV_TXID >", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidGreaterThanOrEqualTo(String value) {
            addCriterion("PREV_TXID >=", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidLessThan(String value) {
            addCriterion("PREV_TXID <", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidLessThanOrEqualTo(String value) {
            addCriterion("PREV_TXID <=", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidLike(String value) {
            addCriterion("PREV_TXID like", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidNotLike(String value) {
            addCriterion("PREV_TXID not like", value, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidIn(List<String> values) {
            addCriterion("PREV_TXID in", values, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidNotIn(List<String> values) {
            addCriterion("PREV_TXID not in", values, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidBetween(String value1, String value2) {
            addCriterion("PREV_TXID between", value1, value2, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andPrevTxidNotBetween(String value1, String value2) {
            addCriterion("PREV_TXID not between", value1, value2, "prevTxid");
            return (Criteria) this;
        }

        public Criteria andIndexInTxIsNull() {
            addCriterion("INDEX_IN_TX is null");
            return (Criteria) this;
        }

        public Criteria andIndexInTxIsNotNull() {
            addCriterion("INDEX_IN_TX is not null");
            return (Criteria) this;
        }

        public Criteria andIndexInTxEqualTo(Integer value) {
            addCriterion("INDEX_IN_TX =", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxNotEqualTo(Integer value) {
            addCriterion("INDEX_IN_TX <>", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxGreaterThan(Integer value) {
            addCriterion("INDEX_IN_TX >", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxGreaterThanOrEqualTo(Integer value) {
            addCriterion("INDEX_IN_TX >=", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxLessThan(Integer value) {
            addCriterion("INDEX_IN_TX <", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxLessThanOrEqualTo(Integer value) {
            addCriterion("INDEX_IN_TX <=", value, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxIn(List<Integer> values) {
            addCriterion("INDEX_IN_TX in", values, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxNotIn(List<Integer> values) {
            addCriterion("INDEX_IN_TX not in", values, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxBetween(Integer value1, Integer value2) {
            addCriterion("INDEX_IN_TX between", value1, value2, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andIndexInTxNotBetween(Integer value1, Integer value2) {
            addCriterion("INDEX_IN_TX not between", value1, value2, "indexInTx");
            return (Criteria) this;
        }

        public Criteria andAddrTypeIsNull() {
            addCriterion("ADDR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAddrTypeIsNotNull() {
            addCriterion("ADDR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAddrTypeEqualTo(String value) {
            addCriterion("ADDR_TYPE =", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeNotEqualTo(String value) {
            addCriterion("ADDR_TYPE <>", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeGreaterThan(String value) {
            addCriterion("ADDR_TYPE >", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ADDR_TYPE >=", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeLessThan(String value) {
            addCriterion("ADDR_TYPE <", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeLessThanOrEqualTo(String value) {
            addCriterion("ADDR_TYPE <=", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeLike(String value) {
            addCriterion("ADDR_TYPE like", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeNotLike(String value) {
            addCriterion("ADDR_TYPE not like", value, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeIn(List<String> values) {
            addCriterion("ADDR_TYPE in", values, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeNotIn(List<String> values) {
            addCriterion("ADDR_TYPE not in", values, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeBetween(String value1, String value2) {
            addCriterion("ADDR_TYPE between", value1, value2, "addrType");
            return (Criteria) this;
        }

        public Criteria andAddrTypeNotBetween(String value1, String value2) {
            addCriterion("ADDR_TYPE not between", value1, value2, "addrType");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdIsNull() {
            addCriterion("NEXT_SCRIPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdIsNotNull() {
            addCriterion("NEXT_SCRIPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdEqualTo(String value) {
            addCriterion("NEXT_SCRIPT_ID =", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdNotEqualTo(String value) {
            addCriterion("NEXT_SCRIPT_ID <>", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdGreaterThan(String value) {
            addCriterion("NEXT_SCRIPT_ID >", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT_SCRIPT_ID >=", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdLessThan(String value) {
            addCriterion("NEXT_SCRIPT_ID <", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdLessThanOrEqualTo(String value) {
            addCriterion("NEXT_SCRIPT_ID <=", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdLike(String value) {
            addCriterion("NEXT_SCRIPT_ID like", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdNotLike(String value) {
            addCriterion("NEXT_SCRIPT_ID not like", value, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdIn(List<String> values) {
            addCriterion("NEXT_SCRIPT_ID in", values, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdNotIn(List<String> values) {
            addCriterion("NEXT_SCRIPT_ID not in", values, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdBetween(String value1, String value2) {
            addCriterion("NEXT_SCRIPT_ID between", value1, value2, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdNotBetween(String value1, String value2) {
            addCriterion("NEXT_SCRIPT_ID not between", value1, value2, "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andSvalueIsNull() {
            addCriterion("SVALUE is null");
            return (Criteria) this;
        }

        public Criteria andSvalueIsNotNull() {
            addCriterion("SVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andSvalueEqualTo(BigDecimal value) {
            addCriterion("SVALUE =", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotEqualTo(BigDecimal value) {
            addCriterion("SVALUE <>", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueGreaterThan(BigDecimal value) {
            addCriterion("SVALUE >", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SVALUE >=", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueLessThan(BigDecimal value) {
            addCriterion("SVALUE <", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SVALUE <=", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueIn(List<BigDecimal> values) {
            addCriterion("SVALUE in", values, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotIn(List<BigDecimal> values) {
            addCriterion("SVALUE not in", values, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVALUE between", value1, value2, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVALUE not between", value1, value2, "svalue");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("FEE is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("FEE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(BigDecimal value) {
            addCriterion("FEE =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(BigDecimal value) {
            addCriterion("FEE <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(BigDecimal value) {
            addCriterion("FEE >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(BigDecimal value) {
            addCriterion("FEE <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<BigDecimal> values) {
            addCriterion("FEE in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<BigDecimal> values) {
            addCriterion("FEE not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andTaxIsNull() {
            addCriterion("TAX is null");
            return (Criteria) this;
        }

        public Criteria andTaxIsNotNull() {
            addCriterion("TAX is not null");
            return (Criteria) this;
        }

        public Criteria andTaxEqualTo(BigDecimal value) {
            addCriterion("TAX =", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotEqualTo(BigDecimal value) {
            addCriterion("TAX <>", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThan(BigDecimal value) {
            addCriterion("TAX >", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TAX >=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThan(BigDecimal value) {
            addCriterion("TAX <", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TAX <=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxIn(List<BigDecimal> values) {
            addCriterion("TAX in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotIn(List<BigDecimal> values) {
            addCriterion("TAX not in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAX between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAX not between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andExtCommentsIsNull() {
            addCriterion("EXT_COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andExtCommentsIsNotNull() {
            addCriterion("EXT_COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andExtCommentsEqualTo(String value) {
            addCriterion("EXT_COMMENTS =", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsNotEqualTo(String value) {
            addCriterion("EXT_COMMENTS <>", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsGreaterThan(String value) {
            addCriterion("EXT_COMMENTS >", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_COMMENTS >=", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsLessThan(String value) {
            addCriterion("EXT_COMMENTS <", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsLessThanOrEqualTo(String value) {
            addCriterion("EXT_COMMENTS <=", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsLike(String value) {
            addCriterion("EXT_COMMENTS like", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsNotLike(String value) {
            addCriterion("EXT_COMMENTS not like", value, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsIn(List<String> values) {
            addCriterion("EXT_COMMENTS in", values, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsNotIn(List<String> values) {
            addCriterion("EXT_COMMENTS not in", values, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsBetween(String value1, String value2) {
            addCriterion("EXT_COMMENTS between", value1, value2, "extComments");
            return (Criteria) this;
        }

        public Criteria andExtCommentsNotBetween(String value1, String value2) {
            addCriterion("EXT_COMMENTS not between", value1, value2, "extComments");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTxidLikeInsensitive(String value) {
            addCriterion("upper(TXID) like", value.toUpperCase(), "txid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLikeInsensitive(String value) {
            addCriterion("upper(LOG_UUID) like", value.toUpperCase(), "logUuid");
            return (Criteria) this;
        }

        public Criteria andAddressLikeInsensitive(String value) {
            addCriterion("upper(ADDRESS) like", value.toUpperCase(), "address");
            return (Criteria) this;
        }

        public Criteria andBversionLikeInsensitive(String value) {
            addCriterion("upper(BVERSION) like", value.toUpperCase(), "bversion");
            return (Criteria) this;
        }

        public Criteria andPrevTxidLikeInsensitive(String value) {
            addCriterion("upper(PREV_TXID) like", value.toUpperCase(), "prevTxid");
            return (Criteria) this;
        }

        public Criteria andAddrTypeLikeInsensitive(String value) {
            addCriterion("upper(ADDR_TYPE) like", value.toUpperCase(), "addrType");
            return (Criteria) this;
        }

        public Criteria andNextScriptIdLikeInsensitive(String value) {
            addCriterion("upper(NEXT_SCRIPT_ID) like", value.toUpperCase(), "nextScriptId");
            return (Criteria) this;
        }

        public Criteria andExtCommentsLikeInsensitive(String value) {
            addCriterion("upper(EXT_COMMENTS) like", value.toUpperCase(), "extComments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 21 20:51:20 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}