package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_BLOCK_MPT")
@AllArgsConstructor
@NoArgsConstructor
public class BCBlockMpt extends BCBlockMptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String bversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal blockHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.HASH_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String hashMpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.HASH_PREV_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String hashPrevMpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.MPT_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String mptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.V_COUNTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer vCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.BLOCK_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String blockStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_BLOCK_MPT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.BVERSION
     *
     * @return the value of BC_BLOCK_MPT.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBversion() {
        return bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.BVERSION
     *
     * @param bversion the value for BC_BLOCK_MPT.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBversion(String bversion) {
        this.bversion = bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.BLOCK_HEIGHT
     *
     * @return the value of BC_BLOCK_MPT.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.BLOCK_HEIGHT
     *
     * @param blockHeight the value for BC_BLOCK_MPT.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBlockHeight(BigDecimal blockHeight) {
        this.blockHeight = blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.HASH_MPT
     *
     * @return the value of BC_BLOCK_MPT.HASH_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getHashMpt() {
        return hashMpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.HASH_MPT
     *
     * @param hashMpt the value for BC_BLOCK_MPT.HASH_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setHashMpt(String hashMpt) {
        this.hashMpt = hashMpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.HASH_PREV_MPT
     *
     * @return the value of BC_BLOCK_MPT.HASH_PREV_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getHashPrevMpt() {
        return hashPrevMpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.HASH_PREV_MPT
     *
     * @param hashPrevMpt the value for BC_BLOCK_MPT.HASH_PREV_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setHashPrevMpt(String hashPrevMpt) {
        this.hashPrevMpt = hashPrevMpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.MPT_TYPE
     *
     * @return the value of BC_BLOCK_MPT.MPT_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getMptType() {
        return mptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.MPT_TYPE
     *
     * @param mptType the value for BC_BLOCK_MPT.MPT_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setMptType(String mptType) {
        this.mptType = mptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.V_COUNTS
     *
     * @return the value of BC_BLOCK_MPT.V_COUNTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getvCounts() {
        return vCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.V_COUNTS
     *
     * @param vCounts the value for BC_BLOCK_MPT.V_COUNTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setvCounts(Integer vCounts) {
        this.vCounts = vCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.BLOCK_STATUS
     *
     * @return the value of BC_BLOCK_MPT.BLOCK_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBlockStatus() {
        return blockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.BLOCK_STATUS
     *
     * @param blockStatus the value for BC_BLOCK_MPT.BLOCK_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBlockStatus(String blockStatus) {
        this.blockStatus = blockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.CREATE_TIME
     *
     * @return the value of BC_BLOCK_MPT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.CREATE_TIME
     *
     * @param createTime the value for BC_BLOCK_MPT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_BLOCK_MPT.UPDATE_TIME
     *
     * @return the value of BC_BLOCK_MPT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_BLOCK_MPT.UPDATE_TIME
     *
     * @param updateTime the value for BC_BLOCK_MPT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCBlockMpt other = (BCBlockMpt) that;
        return (this.getLogUuid() == null ? other.getLogUuid() == null : this.getLogUuid().equals(other.getLogUuid()))
            && (this.getBversion() == null ? other.getBversion() == null : this.getBversion().equals(other.getBversion()))
            && (this.getBlockHeight() == null ? other.getBlockHeight() == null : this.getBlockHeight().equals(other.getBlockHeight()))
            && (this.getHashMpt() == null ? other.getHashMpt() == null : this.getHashMpt().equals(other.getHashMpt()))
            && (this.getHashPrevMpt() == null ? other.getHashPrevMpt() == null : this.getHashPrevMpt().equals(other.getHashPrevMpt()))
            && (this.getMptType() == null ? other.getMptType() == null : this.getMptType().equals(other.getMptType()))
            && (this.getvCounts() == null ? other.getvCounts() == null : this.getvCounts().equals(other.getvCounts()))
            && (this.getBlockStatus() == null ? other.getBlockStatus() == null : this.getBlockStatus().equals(other.getBlockStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogUuid() == null) ? 0 : getLogUuid().hashCode());
        result = prime * result + ((getBversion() == null) ? 0 : getBversion().hashCode());
        result = prime * result + ((getBlockHeight() == null) ? 0 : getBlockHeight().hashCode());
        result = prime * result + ((getHashMpt() == null) ? 0 : getHashMpt().hashCode());
        result = prime * result + ((getHashPrevMpt() == null) ? 0 : getHashPrevMpt().hashCode());
        result = prime * result + ((getMptType() == null) ? 0 : getMptType().hashCode());
        result = prime * result + ((getvCounts() == null) ? 0 : getvCounts().hashCode());
        result = prime * result + ((getBlockStatus() == null) ? 0 : getBlockStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK_MPT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bversion=").append(bversion);
        sb.append(", blockHeight=").append(blockHeight);
        sb.append(", hashMpt=").append(hashMpt);
        sb.append(", hashPrevMpt=").append(hashPrevMpt);
        sb.append(", mptType=").append(mptType);
        sb.append(", vCounts=").append(vCounts);
        sb.append(", blockStatus=").append(blockStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}