package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class BCBlockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BCBlockExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogUuidIsNull() {
            addCriterion("LOG_UUID is null");
            return (Criteria) this;
        }

        public Criteria andLogUuidIsNotNull() {
            addCriterion("LOG_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andLogUuidEqualTo(String value) {
            addCriterion("LOG_UUID =", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotEqualTo(String value) {
            addCriterion("LOG_UUID <>", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThan(String value) {
            addCriterion("LOG_UUID >", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_UUID >=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThan(String value) {
            addCriterion("LOG_UUID <", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLessThanOrEqualTo(String value) {
            addCriterion("LOG_UUID <=", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidLike(String value) {
            addCriterion("LOG_UUID like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotLike(String value) {
            addCriterion("LOG_UUID not like", value, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidIn(List<String> values) {
            addCriterion("LOG_UUID in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotIn(List<String> values) {
            addCriterion("LOG_UUID not in", values, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidBetween(String value1, String value2) {
            addCriterion("LOG_UUID between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andLogUuidNotBetween(String value1, String value2) {
            addCriterion("LOG_UUID not between", value1, value2, "logUuid");
            return (Criteria) this;
        }

        public Criteria andBversionIsNull() {
            addCriterion("BVERSION is null");
            return (Criteria) this;
        }

        public Criteria andBversionIsNotNull() {
            addCriterion("BVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andBversionEqualTo(String value) {
            addCriterion("BVERSION =", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotEqualTo(String value) {
            addCriterion("BVERSION <>", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionGreaterThan(String value) {
            addCriterion("BVERSION >", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionGreaterThanOrEqualTo(String value) {
            addCriterion("BVERSION >=", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLessThan(String value) {
            addCriterion("BVERSION <", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLessThanOrEqualTo(String value) {
            addCriterion("BVERSION <=", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionLike(String value) {
            addCriterion("BVERSION like", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotLike(String value) {
            addCriterion("BVERSION not like", value, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionIn(List<String> values) {
            addCriterion("BVERSION in", values, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotIn(List<String> values) {
            addCriterion("BVERSION not in", values, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionBetween(String value1, String value2) {
            addCriterion("BVERSION between", value1, value2, "bversion");
            return (Criteria) this;
        }

        public Criteria andBversionNotBetween(String value1, String value2) {
            addCriterion("BVERSION not between", value1, value2, "bversion");
            return (Criteria) this;
        }

        public Criteria andSecondIdxIsNull() {
            addCriterion("SECOND_IDX is null");
            return (Criteria) this;
        }

        public Criteria andSecondIdxIsNotNull() {
            addCriterion("SECOND_IDX is not null");
            return (Criteria) this;
        }

        public Criteria andSecondIdxEqualTo(String value) {
            addCriterion("SECOND_IDX =", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxNotEqualTo(String value) {
            addCriterion("SECOND_IDX <>", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxGreaterThan(String value) {
            addCriterion("SECOND_IDX >", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxGreaterThanOrEqualTo(String value) {
            addCriterion("SECOND_IDX >=", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxLessThan(String value) {
            addCriterion("SECOND_IDX <", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxLessThanOrEqualTo(String value) {
            addCriterion("SECOND_IDX <=", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxLike(String value) {
            addCriterion("SECOND_IDX like", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxNotLike(String value) {
            addCriterion("SECOND_IDX not like", value, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxIn(List<String> values) {
            addCriterion("SECOND_IDX in", values, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxNotIn(List<String> values) {
            addCriterion("SECOND_IDX not in", values, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxBetween(String value1, String value2) {
            addCriterion("SECOND_IDX between", value1, value2, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andSecondIdxNotBetween(String value1, String value2) {
            addCriterion("SECOND_IDX not between", value1, value2, "secondIdx");
            return (Criteria) this;
        }

        public Criteria andBhParentHashIsNull() {
            addCriterion("BH_PARENT_HASH is null");
            return (Criteria) this;
        }

        public Criteria andBhParentHashIsNotNull() {
            addCriterion("BH_PARENT_HASH is not null");
            return (Criteria) this;
        }

        public Criteria andBhParentHashEqualTo(String value) {
            addCriterion("BH_PARENT_HASH =", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashNotEqualTo(String value) {
            addCriterion("BH_PARENT_HASH <>", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashGreaterThan(String value) {
            addCriterion("BH_PARENT_HASH >", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashGreaterThanOrEqualTo(String value) {
            addCriterion("BH_PARENT_HASH >=", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashLessThan(String value) {
            addCriterion("BH_PARENT_HASH <", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashLessThanOrEqualTo(String value) {
            addCriterion("BH_PARENT_HASH <=", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashLike(String value) {
            addCriterion("BH_PARENT_HASH like", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashNotLike(String value) {
            addCriterion("BH_PARENT_HASH not like", value, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashIn(List<String> values) {
            addCriterion("BH_PARENT_HASH in", values, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashNotIn(List<String> values) {
            addCriterion("BH_PARENT_HASH not in", values, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashBetween(String value1, String value2) {
            addCriterion("BH_PARENT_HASH between", value1, value2, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhParentHashNotBetween(String value1, String value2) {
            addCriterion("BH_PARENT_HASH not between", value1, value2, "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhStateRootIsNull() {
            addCriterion("BH_STATE_ROOT is null");
            return (Criteria) this;
        }

        public Criteria andBhStateRootIsNotNull() {
            addCriterion("BH_STATE_ROOT is not null");
            return (Criteria) this;
        }

        public Criteria andBhStateRootEqualTo(String value) {
            addCriterion("BH_STATE_ROOT =", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootNotEqualTo(String value) {
            addCriterion("BH_STATE_ROOT <>", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootGreaterThan(String value) {
            addCriterion("BH_STATE_ROOT >", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootGreaterThanOrEqualTo(String value) {
            addCriterion("BH_STATE_ROOT >=", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootLessThan(String value) {
            addCriterion("BH_STATE_ROOT <", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootLessThanOrEqualTo(String value) {
            addCriterion("BH_STATE_ROOT <=", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootLike(String value) {
            addCriterion("BH_STATE_ROOT like", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootNotLike(String value) {
            addCriterion("BH_STATE_ROOT not like", value, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootIn(List<String> values) {
            addCriterion("BH_STATE_ROOT in", values, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootNotIn(List<String> values) {
            addCriterion("BH_STATE_ROOT not in", values, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootBetween(String value1, String value2) {
            addCriterion("BH_STATE_ROOT between", value1, value2, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhStateRootNotBetween(String value1, String value2) {
            addCriterion("BH_STATE_ROOT not between", value1, value2, "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashIsNull() {
            addCriterion("BH_BLOCK_HASH is null");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashIsNotNull() {
            addCriterion("BH_BLOCK_HASH is not null");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashEqualTo(String value) {
            addCriterion("BH_BLOCK_HASH =", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashNotEqualTo(String value) {
            addCriterion("BH_BLOCK_HASH <>", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashGreaterThan(String value) {
            addCriterion("BH_BLOCK_HASH >", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashGreaterThanOrEqualTo(String value) {
            addCriterion("BH_BLOCK_HASH >=", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashLessThan(String value) {
            addCriterion("BH_BLOCK_HASH <", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashLessThanOrEqualTo(String value) {
            addCriterion("BH_BLOCK_HASH <=", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashLike(String value) {
            addCriterion("BH_BLOCK_HASH like", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashNotLike(String value) {
            addCriterion("BH_BLOCK_HASH not like", value, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashIn(List<String> values) {
            addCriterion("BH_BLOCK_HASH in", values, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashNotIn(List<String> values) {
            addCriterion("BH_BLOCK_HASH not in", values, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashBetween(String value1, String value2) {
            addCriterion("BH_BLOCK_HASH between", value1, value2, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashNotBetween(String value1, String value2) {
            addCriterion("BH_BLOCK_HASH not between", value1, value2, "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootIsNull() {
            addCriterion("BH_TXT_RIEROOT is null");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootIsNotNull() {
            addCriterion("BH_TXT_RIEROOT is not null");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootEqualTo(String value) {
            addCriterion("BH_TXT_RIEROOT =", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootNotEqualTo(String value) {
            addCriterion("BH_TXT_RIEROOT <>", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootGreaterThan(String value) {
            addCriterion("BH_TXT_RIEROOT >", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootGreaterThanOrEqualTo(String value) {
            addCriterion("BH_TXT_RIEROOT >=", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootLessThan(String value) {
            addCriterion("BH_TXT_RIEROOT <", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootLessThanOrEqualTo(String value) {
            addCriterion("BH_TXT_RIEROOT <=", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootLike(String value) {
            addCriterion("BH_TXT_RIEROOT like", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootNotLike(String value) {
            addCriterion("BH_TXT_RIEROOT not like", value, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootIn(List<String> values) {
            addCriterion("BH_TXT_RIEROOT in", values, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootNotIn(List<String> values) {
            addCriterion("BH_TXT_RIEROOT not in", values, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootBetween(String value1, String value2) {
            addCriterion("BH_TXT_RIEROOT between", value1, value2, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootNotBetween(String value1, String value2) {
            addCriterion("BH_TXT_RIEROOT not between", value1, value2, "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootIsNull() {
            addCriterion("BH_RECEIPT_TRIEROOT is null");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootIsNotNull() {
            addCriterion("BH_RECEIPT_TRIEROOT is not null");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootEqualTo(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT =", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootNotEqualTo(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT <>", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootGreaterThan(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT >", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootGreaterThanOrEqualTo(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT >=", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootLessThan(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT <", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootLessThanOrEqualTo(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT <=", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootLike(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT like", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootNotLike(String value) {
            addCriterion("BH_RECEIPT_TRIEROOT not like", value, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootIn(List<String> values) {
            addCriterion("BH_RECEIPT_TRIEROOT in", values, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootNotIn(List<String> values) {
            addCriterion("BH_RECEIPT_TRIEROOT not in", values, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootBetween(String value1, String value2) {
            addCriterion("BH_RECEIPT_TRIEROOT between", value1, value2, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootNotBetween(String value1, String value2) {
            addCriterion("BH_RECEIPT_TRIEROOT not between", value1, value2, "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhTimestampIsNull() {
            addCriterion("BH_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andBhTimestampIsNotNull() {
            addCriterion("BH_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andBhTimestampEqualTo(BigDecimal value) {
            addCriterion("BH_TIMESTAMP =", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampNotEqualTo(BigDecimal value) {
            addCriterion("BH_TIMESTAMP <>", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampGreaterThan(BigDecimal value) {
            addCriterion("BH_TIMESTAMP >", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BH_TIMESTAMP >=", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampLessThan(BigDecimal value) {
            addCriterion("BH_TIMESTAMP <", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BH_TIMESTAMP <=", value, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampIn(List<BigDecimal> values) {
            addCriterion("BH_TIMESTAMP in", values, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampNotIn(List<BigDecimal> values) {
            addCriterion("BH_TIMESTAMP not in", values, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BH_TIMESTAMP between", value1, value2, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhTimestampNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BH_TIMESTAMP not between", value1, value2, "bhTimestamp");
            return (Criteria) this;
        }

        public Criteria andBhNumberIsNull() {
            addCriterion("BH_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andBhNumberIsNotNull() {
            addCriterion("BH_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andBhNumberEqualTo(BigDecimal value) {
            addCriterion("BH_NUMBER =", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberNotEqualTo(BigDecimal value) {
            addCriterion("BH_NUMBER <>", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberGreaterThan(BigDecimal value) {
            addCriterion("BH_NUMBER >", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BH_NUMBER >=", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberLessThan(BigDecimal value) {
            addCriterion("BH_NUMBER <", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BH_NUMBER <=", value, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberIn(List<BigDecimal> values) {
            addCriterion("BH_NUMBER in", values, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberNotIn(List<BigDecimal> values) {
            addCriterion("BH_NUMBER not in", values, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BH_NUMBER between", value1, value2, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhNumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BH_NUMBER not between", value1, value2, "bhNumber");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountIsNull() {
            addCriterion("BH_TXN_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountIsNotNull() {
            addCriterion("BH_TXN_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountEqualTo(Integer value) {
            addCriterion("BH_TXN_COUNT =", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountNotEqualTo(Integer value) {
            addCriterion("BH_TXN_COUNT <>", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountGreaterThan(Integer value) {
            addCriterion("BH_TXN_COUNT >", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("BH_TXN_COUNT >=", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountLessThan(Integer value) {
            addCriterion("BH_TXN_COUNT <", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountLessThanOrEqualTo(Integer value) {
            addCriterion("BH_TXN_COUNT <=", value, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountIn(List<Integer> values) {
            addCriterion("BH_TXN_COUNT in", values, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountNotIn(List<Integer> values) {
            addCriterion("BH_TXN_COUNT not in", values, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountBetween(Integer value1, Integer value2) {
            addCriterion("BH_TXN_COUNT between", value1, value2, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhTxnCountNotBetween(Integer value1, Integer value2) {
            addCriterion("BH_TXN_COUNT not between", value1, value2, "bhTxnCount");
            return (Criteria) this;
        }

        public Criteria andBhSliceidIsNull() {
            addCriterion("BH_SLICEID is null");
            return (Criteria) this;
        }

        public Criteria andBhSliceidIsNotNull() {
            addCriterion("BH_SLICEID is not null");
            return (Criteria) this;
        }

        public Criteria andBhSliceidEqualTo(Integer value) {
            addCriterion("BH_SLICEID =", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidNotEqualTo(Integer value) {
            addCriterion("BH_SLICEID <>", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidGreaterThan(Integer value) {
            addCriterion("BH_SLICEID >", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("BH_SLICEID >=", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidLessThan(Integer value) {
            addCriterion("BH_SLICEID <", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidLessThanOrEqualTo(Integer value) {
            addCriterion("BH_SLICEID <=", value, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidIn(List<Integer> values) {
            addCriterion("BH_SLICEID in", values, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidNotIn(List<Integer> values) {
            addCriterion("BH_SLICEID not in", values, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidBetween(Integer value1, Integer value2) {
            addCriterion("BH_SLICEID between", value1, value2, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhSliceidNotBetween(Integer value1, Integer value2) {
            addCriterion("BH_SLICEID not between", value1, value2, "bhSliceid");
            return (Criteria) this;
        }

        public Criteria andBhExtradataIsNull() {
            addCriterion("BH_EXTRADATA is null");
            return (Criteria) this;
        }

        public Criteria andBhExtradataIsNotNull() {
            addCriterion("BH_EXTRADATA is not null");
            return (Criteria) this;
        }

        public Criteria andBhExtradataEqualTo(String value) {
            addCriterion("BH_EXTRADATA =", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataNotEqualTo(String value) {
            addCriterion("BH_EXTRADATA <>", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataGreaterThan(String value) {
            addCriterion("BH_EXTRADATA >", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataGreaterThanOrEqualTo(String value) {
            addCriterion("BH_EXTRADATA >=", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataLessThan(String value) {
            addCriterion("BH_EXTRADATA <", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataLessThanOrEqualTo(String value) {
            addCriterion("BH_EXTRADATA <=", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataLike(String value) {
            addCriterion("BH_EXTRADATA like", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataNotLike(String value) {
            addCriterion("BH_EXTRADATA not like", value, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataIn(List<String> values) {
            addCriterion("BH_EXTRADATA in", values, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataNotIn(List<String> values) {
            addCriterion("BH_EXTRADATA not in", values, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataBetween(String value1, String value2) {
            addCriterion("BH_EXTRADATA between", value1, value2, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBhExtradataNotBetween(String value1, String value2) {
            addCriterion("BH_EXTRADATA not between", value1, value2, "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBmNodeIsNull() {
            addCriterion("BM_NODE is null");
            return (Criteria) this;
        }

        public Criteria andBmNodeIsNotNull() {
            addCriterion("BM_NODE is not null");
            return (Criteria) this;
        }

        public Criteria andBmNodeEqualTo(String value) {
            addCriterion("BM_NODE =", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeNotEqualTo(String value) {
            addCriterion("BM_NODE <>", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeGreaterThan(String value) {
            addCriterion("BM_NODE >", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeGreaterThanOrEqualTo(String value) {
            addCriterion("BM_NODE >=", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeLessThan(String value) {
            addCriterion("BM_NODE <", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeLessThanOrEqualTo(String value) {
            addCriterion("BM_NODE <=", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeLike(String value) {
            addCriterion("BM_NODE like", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeNotLike(String value) {
            addCriterion("BM_NODE not like", value, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeIn(List<String> values) {
            addCriterion("BM_NODE in", values, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeNotIn(List<String> values) {
            addCriterion("BM_NODE not in", values, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeBetween(String value1, String value2) {
            addCriterion("BM_NODE between", value1, value2, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmNodeNotBetween(String value1, String value2) {
            addCriterion("BM_NODE not between", value1, value2, "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexIsNull() {
            addCriterion("BM_REWARD_HEX is null");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexIsNotNull() {
            addCriterion("BM_REWARD_HEX is not null");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexEqualTo(String value) {
            addCriterion("BM_REWARD_HEX =", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexNotEqualTo(String value) {
            addCriterion("BM_REWARD_HEX <>", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexGreaterThan(String value) {
            addCriterion("BM_REWARD_HEX >", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexGreaterThanOrEqualTo(String value) {
            addCriterion("BM_REWARD_HEX >=", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexLessThan(String value) {
            addCriterion("BM_REWARD_HEX <", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexLessThanOrEqualTo(String value) {
            addCriterion("BM_REWARD_HEX <=", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexLike(String value) {
            addCriterion("BM_REWARD_HEX like", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexNotLike(String value) {
            addCriterion("BM_REWARD_HEX not like", value, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexIn(List<String> values) {
            addCriterion("BM_REWARD_HEX in", values, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexNotIn(List<String> values) {
            addCriterion("BM_REWARD_HEX not in", values, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexBetween(String value1, String value2) {
            addCriterion("BM_REWARD_HEX between", value1, value2, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexNotBetween(String value1, String value2) {
            addCriterion("BM_REWARD_HEX not between", value1, value2, "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmAddressIsNull() {
            addCriterion("BM_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andBmAddressIsNotNull() {
            addCriterion("BM_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andBmAddressEqualTo(String value) {
            addCriterion("BM_ADDRESS =", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressNotEqualTo(String value) {
            addCriterion("BM_ADDRESS <>", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressGreaterThan(String value) {
            addCriterion("BM_ADDRESS >", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressGreaterThanOrEqualTo(String value) {
            addCriterion("BM_ADDRESS >=", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressLessThan(String value) {
            addCriterion("BM_ADDRESS <", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressLessThanOrEqualTo(String value) {
            addCriterion("BM_ADDRESS <=", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressLike(String value) {
            addCriterion("BM_ADDRESS like", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressNotLike(String value) {
            addCriterion("BM_ADDRESS not like", value, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressIn(List<String> values) {
            addCriterion("BM_ADDRESS in", values, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressNotIn(List<String> values) {
            addCriterion("BM_ADDRESS not in", values, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressBetween(String value1, String value2) {
            addCriterion("BM_ADDRESS between", value1, value2, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmAddressNotBetween(String value1, String value2) {
            addCriterion("BM_ADDRESS not between", value1, value2, "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmBcuidIsNull() {
            addCriterion("BM_BCUID is null");
            return (Criteria) this;
        }

        public Criteria andBmBcuidIsNotNull() {
            addCriterion("BM_BCUID is not null");
            return (Criteria) this;
        }

        public Criteria andBmBcuidEqualTo(String value) {
            addCriterion("BM_BCUID =", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidNotEqualTo(String value) {
            addCriterion("BM_BCUID <>", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidGreaterThan(String value) {
            addCriterion("BM_BCUID >", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidGreaterThanOrEqualTo(String value) {
            addCriterion("BM_BCUID >=", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidLessThan(String value) {
            addCriterion("BM_BCUID <", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidLessThanOrEqualTo(String value) {
            addCriterion("BM_BCUID <=", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidLike(String value) {
            addCriterion("BM_BCUID like", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidNotLike(String value) {
            addCriterion("BM_BCUID not like", value, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidIn(List<String> values) {
            addCriterion("BM_BCUID in", values, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidNotIn(List<String> values) {
            addCriterion("BM_BCUID not in", values, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidBetween(String value1, String value2) {
            addCriterion("BM_BCUID between", value1, value2, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBmBcuidNotBetween(String value1, String value2) {
            addCriterion("BM_BCUID not between", value1, value2, "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIsNull() {
            addCriterion("BLOCK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIsNotNull() {
            addCriterion("BLOCK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andBlockStatusEqualTo(String value) {
            addCriterion("BLOCK_STATUS =", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotEqualTo(String value) {
            addCriterion("BLOCK_STATUS <>", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusGreaterThan(String value) {
            addCriterion("BLOCK_STATUS >", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_STATUS >=", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLessThan(String value) {
            addCriterion("BLOCK_STATUS <", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_STATUS <=", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLike(String value) {
            addCriterion("BLOCK_STATUS like", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotLike(String value) {
            addCriterion("BLOCK_STATUS not like", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIn(List<String> values) {
            addCriterion("BLOCK_STATUS in", values, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotIn(List<String> values) {
            addCriterion("BLOCK_STATUS not in", values, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusBetween(String value1, String value2) {
            addCriterion("BLOCK_STATUS between", value1, value2, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotBetween(String value1, String value2) {
            addCriterion("BLOCK_STATUS not between", value1, value2, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andLogUuidLikeInsensitive(String value) {
            addCriterion("upper(LOG_UUID) like", value.toUpperCase(), "logUuid");
            return (Criteria) this;
        }

        public Criteria andBversionLikeInsensitive(String value) {
            addCriterion("upper(BVERSION) like", value.toUpperCase(), "bversion");
            return (Criteria) this;
        }

        public Criteria andSecondIdxLikeInsensitive(String value) {
            addCriterion("upper(SECOND_IDX) like", value.toUpperCase(), "secondIdx");
            return (Criteria) this;
        }

        public Criteria andBhParentHashLikeInsensitive(String value) {
            addCriterion("upper(BH_PARENT_HASH) like", value.toUpperCase(), "bhParentHash");
            return (Criteria) this;
        }

        public Criteria andBhStateRootLikeInsensitive(String value) {
            addCriterion("upper(BH_STATE_ROOT) like", value.toUpperCase(), "bhStateRoot");
            return (Criteria) this;
        }

        public Criteria andBhBlockHashLikeInsensitive(String value) {
            addCriterion("upper(BH_BLOCK_HASH) like", value.toUpperCase(), "bhBlockHash");
            return (Criteria) this;
        }

        public Criteria andBhTxtRierootLikeInsensitive(String value) {
            addCriterion("upper(BH_TXT_RIEROOT) like", value.toUpperCase(), "bhTxtRieroot");
            return (Criteria) this;
        }

        public Criteria andBhReceiptTrierootLikeInsensitive(String value) {
            addCriterion("upper(BH_RECEIPT_TRIEROOT) like", value.toUpperCase(), "bhReceiptTrieroot");
            return (Criteria) this;
        }

        public Criteria andBhExtradataLikeInsensitive(String value) {
            addCriterion("upper(BH_EXTRADATA) like", value.toUpperCase(), "bhExtradata");
            return (Criteria) this;
        }

        public Criteria andBmNodeLikeInsensitive(String value) {
            addCriterion("upper(BM_NODE) like", value.toUpperCase(), "bmNode");
            return (Criteria) this;
        }

        public Criteria andBmRewardHexLikeInsensitive(String value) {
            addCriterion("upper(BM_REWARD_HEX) like", value.toUpperCase(), "bmRewardHex");
            return (Criteria) this;
        }

        public Criteria andBmAddressLikeInsensitive(String value) {
            addCriterion("upper(BM_ADDRESS) like", value.toUpperCase(), "bmAddress");
            return (Criteria) this;
        }

        public Criteria andBmBcuidLikeInsensitive(String value) {
            addCriterion("upper(BM_BCUID) like", value.toUpperCase(), "bmBcuid");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLikeInsensitive(String value) {
            addCriterion("upper(BLOCK_STATUS) like", value.toUpperCase(), "blockStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_BLOCK
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 21 20:42:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BC_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}