package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_CRYPTO_TOKEN_DATA")
@AllArgsConstructor
@NoArgsConstructor
public class BCCryptoTokenData extends BCCryptoTokenDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.TOTALS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal totals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.TOKEN_NAME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.TOKEN_CODE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.EXTRADATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String extradata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.TOKEN_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_CRYPTO_TOKEN_DATA.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.TOTALS
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.TOTALS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getTotals() {
        return totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.TOTALS
     *
     * @param totals the value for BC_CRYPTO_TOKEN_DATA.TOTALS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTotals(BigDecimal totals) {
        this.totals = totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_SYMBOL
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenSymbol() {
        return tokenSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_SYMBOL
     *
     * @param tokenSymbol the value for BC_CRYPTO_TOKEN_DATA.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenSymbol(String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_NAME
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.TOKEN_NAME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenName() {
        return tokenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_NAME
     *
     * @param tokenName the value for BC_CRYPTO_TOKEN_DATA.TOKEN_NAME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenName(String tokenName) {
        this.tokenName = tokenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_CODE
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.TOKEN_CODE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenCode() {
        return tokenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_CODE
     *
     * @param tokenCode the value for BC_CRYPTO_TOKEN_DATA.TOKEN_CODE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenCode(String tokenCode) {
        this.tokenCode = tokenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.EXTRADATA
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.EXTRADATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getExtradata() {
        return extradata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.EXTRADATA
     *
     * @param extradata the value for BC_CRYPTO_TOKEN_DATA.EXTRADATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setExtradata(String extradata) {
        this.extradata = extradata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_STATUS
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.TOKEN_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenStatus() {
        return tokenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.TOKEN_STATUS
     *
     * @param tokenStatus the value for BC_CRYPTO_TOKEN_DATA.TOKEN_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenStatus(String tokenStatus) {
        this.tokenStatus = tokenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.CREATE_TIME
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.CREATE_TIME
     *
     * @param createTime the value for BC_CRYPTO_TOKEN_DATA.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_CRYPTO_TOKEN_DATA.UPDATE_TIME
     *
     * @return the value of BC_CRYPTO_TOKEN_DATA.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_CRYPTO_TOKEN_DATA.UPDATE_TIME
     *
     * @param updateTime the value for BC_CRYPTO_TOKEN_DATA.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_CRYPTO_TOKEN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCCryptoTokenData other = (BCCryptoTokenData) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
            && (this.getTotals() == null ? other.getTotals() == null : this.getTotals().equals(other.getTotals()))
            && (this.getTokenSymbol() == null ? other.getTokenSymbol() == null : this.getTokenSymbol().equals(other.getTokenSymbol()))
            && (this.getTokenName() == null ? other.getTokenName() == null : this.getTokenName().equals(other.getTokenName()))
            && (this.getTokenCode() == null ? other.getTokenCode() == null : this.getTokenCode().equals(other.getTokenCode()))
            && (this.getExtradata() == null ? other.getExtradata() == null : this.getExtradata().equals(other.getExtradata()))
            && (this.getTokenStatus() == null ? other.getTokenStatus() == null : this.getTokenStatus().equals(other.getTokenStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_CRYPTO_TOKEN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getTotals() == null) ? 0 : getTotals().hashCode());
        result = prime * result + ((getTokenSymbol() == null) ? 0 : getTokenSymbol().hashCode());
        result = prime * result + ((getTokenName() == null) ? 0 : getTokenName().hashCode());
        result = prime * result + ((getTokenCode() == null) ? 0 : getTokenCode().hashCode());
        result = prime * result + ((getExtradata() == null) ? 0 : getExtradata().hashCode());
        result = prime * result + ((getTokenStatus() == null) ? 0 : getTokenStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_CRYPTO_TOKEN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", totals=").append(totals);
        sb.append(", tokenSymbol=").append(tokenSymbol);
        sb.append(", tokenName=").append(tokenName);
        sb.append(", tokenCode=").append(tokenCode);
        sb.append(", extradata=").append(extradata);
        sb.append(", tokenStatus=").append(tokenStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}