package org.brewchain.backend.ordbgens.bc.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_MTX_SIGNATURE")
@AllArgsConstructor
@NoArgsConstructor
public class BCMtxSignature extends BCMtxSignatureKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String bcAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String mtxHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.SIGN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String signData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String txStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer indexInTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_SIGNATURE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.BC_ADDRESS
     *
     * @return the value of BC_MTX_SIGNATURE.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBcAddress() {
        return bcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.BC_ADDRESS
     *
     * @param bcAddress the value for BC_MTX_SIGNATURE.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBcAddress(String bcAddress) {
        this.bcAddress = bcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.MTX_HASH
     *
     * @return the value of BC_MTX_SIGNATURE.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getMtxHash() {
        return mtxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.MTX_HASH
     *
     * @param mtxHash the value for BC_MTX_SIGNATURE.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setMtxHash(String mtxHash) {
        this.mtxHash = mtxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.SIGN_DATA
     *
     * @return the value of BC_MTX_SIGNATURE.SIGN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getSignData() {
        return signData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.SIGN_DATA
     *
     * @param signData the value for BC_MTX_SIGNATURE.SIGN_DATA
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setSignData(String signData) {
        this.signData = signData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.TX_STATUS
     *
     * @return the value of BC_MTX_SIGNATURE.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTxStatus() {
        return txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.TX_STATUS
     *
     * @param txStatus the value for BC_MTX_SIGNATURE.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTxStatus(String txStatus) {
        this.txStatus = txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.INDEX_IN_TX
     *
     * @return the value of BC_MTX_SIGNATURE.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getIndexInTx() {
        return indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.INDEX_IN_TX
     *
     * @param indexInTx the value for BC_MTX_SIGNATURE.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setIndexInTx(Integer indexInTx) {
        this.indexInTx = indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.CREATE_TIME
     *
     * @return the value of BC_MTX_SIGNATURE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.CREATE_TIME
     *
     * @param createTime the value for BC_MTX_SIGNATURE.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_SIGNATURE.UPDATE_TIME
     *
     * @return the value of BC_MTX_SIGNATURE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_SIGNATURE.UPDATE_TIME
     *
     * @param updateTime the value for BC_MTX_SIGNATURE.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCMtxSignature other = (BCMtxSignature) that;
        return (this.getMtxSignid() == null ? other.getMtxSignid() == null : this.getMtxSignid().equals(other.getMtxSignid()))
            && (this.getBcAddress() == null ? other.getBcAddress() == null : this.getBcAddress().equals(other.getBcAddress()))
            && (this.getMtxHash() == null ? other.getMtxHash() == null : this.getMtxHash().equals(other.getMtxHash()))
            && (this.getSignData() == null ? other.getSignData() == null : this.getSignData().equals(other.getSignData()))
            && (this.getTxStatus() == null ? other.getTxStatus() == null : this.getTxStatus().equals(other.getTxStatus()))
            && (this.getIndexInTx() == null ? other.getIndexInTx() == null : this.getIndexInTx().equals(other.getIndexInTx()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMtxSignid() == null) ? 0 : getMtxSignid().hashCode());
        result = prime * result + ((getBcAddress() == null) ? 0 : getBcAddress().hashCode());
        result = prime * result + ((getMtxHash() == null) ? 0 : getMtxHash().hashCode());
        result = prime * result + ((getSignData() == null) ? 0 : getSignData().hashCode());
        result = prime * result + ((getTxStatus() == null) ? 0 : getTxStatus().hashCode());
        result = prime * result + ((getIndexInTx() == null) ? 0 : getIndexInTx().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_SIGNATURE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bcAddress=").append(bcAddress);
        sb.append(", mtxHash=").append(mtxHash);
        sb.append(", signData=").append(signData);
        sb.append(", txStatus=").append(txStatus);
        sb.append(", indexInTx=").append(indexInTx);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}