package org.brewchain.backend.ordbgens.bc.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class BCMtxOutputKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_OUTPUT.MTX_OUTPUTID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String mtxOutputid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_OUTPUT.MTX_OUTPUTID
     *
     * @return the value of BC_MTX_OUTPUT.MTX_OUTPUTID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getMtxOutputid() {
        return mtxOutputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_OUTPUT.MTX_OUTPUTID
     *
     * @param mtxOutputid the value for BC_MTX_OUTPUT.MTX_OUTPUTID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setMtxOutputid(String mtxOutputid) {
        this.mtxOutputid = mtxOutputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCMtxOutputKey other = (BCMtxOutputKey) that;
        return (this.getMtxOutputid() == null ? other.getMtxOutputid() == null : this.getMtxOutputid().equals(other.getMtxOutputid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMtxOutputid() == null) ? 0 : getMtxOutputid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_OUTPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mtxOutputid=").append(mtxOutputid);
        sb.append("]");
        return sb.toString();
    }
}