package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_MTX_INPUT")
@AllArgsConstructor
@NoArgsConstructor
public class BCMtxInput extends BCMtxInputKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String bcAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String mtxHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.BC_NONCE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer bcNonce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.AMOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.TOKEN_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String tokenSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.CRYPTO_TOKEN_HEX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String cryptoTokenHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String txStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer indexInTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_MTX_INPUT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.BC_ADDRESS
     *
     * @return the value of BC_MTX_INPUT.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBcAddress() {
        return bcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.BC_ADDRESS
     *
     * @param bcAddress the value for BC_MTX_INPUT.BC_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBcAddress(String bcAddress) {
        this.bcAddress = bcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.MTX_HASH
     *
     * @return the value of BC_MTX_INPUT.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getMtxHash() {
        return mtxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.MTX_HASH
     *
     * @param mtxHash the value for BC_MTX_INPUT.MTX_HASH
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setMtxHash(String mtxHash) {
        this.mtxHash = mtxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.BC_NONCE
     *
     * @return the value of BC_MTX_INPUT.BC_NONCE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getBcNonce() {
        return bcNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.BC_NONCE
     *
     * @param bcNonce the value for BC_MTX_INPUT.BC_NONCE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBcNonce(Integer bcNonce) {
        this.bcNonce = bcNonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.AMOUNT
     *
     * @return the value of BC_MTX_INPUT.AMOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.AMOUNT
     *
     * @param amount the value for BC_MTX_INPUT.AMOUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.TOKEN_ID
     *
     * @return the value of BC_MTX_INPUT.TOKEN_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.TOKEN_ID
     *
     * @param tokenId the value for BC_MTX_INPUT.TOKEN_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.TOKEN_SYMBOL
     *
     * @return the value of BC_MTX_INPUT.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTokenSymbol() {
        return tokenSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.TOKEN_SYMBOL
     *
     * @param tokenSymbol the value for BC_MTX_INPUT.TOKEN_SYMBOL
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTokenSymbol(String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.CRYPTO_TOKEN_HEX
     *
     * @return the value of BC_MTX_INPUT.CRYPTO_TOKEN_HEX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getCryptoTokenHex() {
        return cryptoTokenHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.CRYPTO_TOKEN_HEX
     *
     * @param cryptoTokenHex the value for BC_MTX_INPUT.CRYPTO_TOKEN_HEX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCryptoTokenHex(String cryptoTokenHex) {
        this.cryptoTokenHex = cryptoTokenHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.TX_STATUS
     *
     * @return the value of BC_MTX_INPUT.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTxStatus() {
        return txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.TX_STATUS
     *
     * @param txStatus the value for BC_MTX_INPUT.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTxStatus(String txStatus) {
        this.txStatus = txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.INDEX_IN_TX
     *
     * @return the value of BC_MTX_INPUT.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getIndexInTx() {
        return indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.INDEX_IN_TX
     *
     * @param indexInTx the value for BC_MTX_INPUT.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setIndexInTx(Integer indexInTx) {
        this.indexInTx = indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.CREATE_TIME
     *
     * @return the value of BC_MTX_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.CREATE_TIME
     *
     * @param createTime the value for BC_MTX_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_MTX_INPUT.UPDATE_TIME
     *
     * @return the value of BC_MTX_INPUT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_MTX_INPUT.UPDATE_TIME
     *
     * @param updateTime the value for BC_MTX_INPUT.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_INPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCMtxInput other = (BCMtxInput) that;
        return (this.getMtxInputid() == null ? other.getMtxInputid() == null : this.getMtxInputid().equals(other.getMtxInputid()))
            && (this.getBcAddress() == null ? other.getBcAddress() == null : this.getBcAddress().equals(other.getBcAddress()))
            && (this.getMtxHash() == null ? other.getMtxHash() == null : this.getMtxHash().equals(other.getMtxHash()))
            && (this.getBcNonce() == null ? other.getBcNonce() == null : this.getBcNonce().equals(other.getBcNonce()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
            && (this.getTokenSymbol() == null ? other.getTokenSymbol() == null : this.getTokenSymbol().equals(other.getTokenSymbol()))
            && (this.getCryptoTokenHex() == null ? other.getCryptoTokenHex() == null : this.getCryptoTokenHex().equals(other.getCryptoTokenHex()))
            && (this.getTxStatus() == null ? other.getTxStatus() == null : this.getTxStatus().equals(other.getTxStatus()))
            && (this.getIndexInTx() == null ? other.getIndexInTx() == null : this.getIndexInTx().equals(other.getIndexInTx()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_INPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMtxInputid() == null) ? 0 : getMtxInputid().hashCode());
        result = prime * result + ((getBcAddress() == null) ? 0 : getBcAddress().hashCode());
        result = prime * result + ((getMtxHash() == null) ? 0 : getMtxHash().hashCode());
        result = prime * result + ((getBcNonce() == null) ? 0 : getBcNonce().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getTokenSymbol() == null) ? 0 : getTokenSymbol().hashCode());
        result = prime * result + ((getCryptoTokenHex() == null) ? 0 : getCryptoTokenHex().hashCode());
        result = prime * result + ((getTxStatus() == null) ? 0 : getTxStatus().hashCode());
        result = prime * result + ((getIndexInTx() == null) ? 0 : getIndexInTx().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_MTX_INPUT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bcAddress=").append(bcAddress);
        sb.append(", mtxHash=").append(mtxHash);
        sb.append(", bcNonce=").append(bcNonce);
        sb.append(", amount=").append(amount);
        sb.append(", tokenId=").append(tokenId);
        sb.append(", tokenSymbol=").append(tokenSymbol);
        sb.append(", cryptoTokenHex=").append(cryptoTokenHex);
        sb.append(", txStatus=").append(txStatus);
        sb.append(", indexInTx=").append(indexInTx);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}