package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_TRANSACTON")
@AllArgsConstructor
@NoArgsConstructor
public class BCTransacton extends BCTransactonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String bversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.HASH_MERKLE_ROOT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String hashMerkleRoot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal blockHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.ADDRESS_IN_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer addressInCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.ADDRESS_OUT_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer addressOutCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.PROP_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer propCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String txStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.INDEX_IN_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer indexInBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String extComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.BVERSION
     *
     * @return the value of BC_TRANSACTON.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBversion() {
        return bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.BVERSION
     *
     * @param bversion the value for BC_TRANSACTON.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBversion(String bversion) {
        this.bversion = bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.HASH_MERKLE_ROOT
     *
     * @return the value of BC_TRANSACTON.HASH_MERKLE_ROOT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getHashMerkleRoot() {
        return hashMerkleRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.HASH_MERKLE_ROOT
     *
     * @param hashMerkleRoot the value for BC_TRANSACTON.HASH_MERKLE_ROOT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setHashMerkleRoot(String hashMerkleRoot) {
        this.hashMerkleRoot = hashMerkleRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.BLOCK_HEIGHT
     *
     * @return the value of BC_TRANSACTON.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.BLOCK_HEIGHT
     *
     * @param blockHeight the value for BC_TRANSACTON.BLOCK_HEIGHT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBlockHeight(BigDecimal blockHeight) {
        this.blockHeight = blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.ADDRESS_IN_COUNT
     *
     * @return the value of BC_TRANSACTON.ADDRESS_IN_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getAddressInCount() {
        return addressInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.ADDRESS_IN_COUNT
     *
     * @param addressInCount the value for BC_TRANSACTON.ADDRESS_IN_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setAddressInCount(Integer addressInCount) {
        this.addressInCount = addressInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.ADDRESS_OUT_COUNT
     *
     * @return the value of BC_TRANSACTON.ADDRESS_OUT_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getAddressOutCount() {
        return addressOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.ADDRESS_OUT_COUNT
     *
     * @param addressOutCount the value for BC_TRANSACTON.ADDRESS_OUT_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setAddressOutCount(Integer addressOutCount) {
        this.addressOutCount = addressOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.PROP_COUNT
     *
     * @return the value of BC_TRANSACTON.PROP_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getPropCount() {
        return propCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.PROP_COUNT
     *
     * @param propCount the value for BC_TRANSACTON.PROP_COUNT
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setPropCount(Integer propCount) {
        this.propCount = propCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.TX_STATUS
     *
     * @return the value of BC_TRANSACTON.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getTxStatus() {
        return txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.TX_STATUS
     *
     * @param txStatus the value for BC_TRANSACTON.TX_STATUS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTxStatus(String txStatus) {
        this.txStatus = txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.INDEX_IN_BLOCK
     *
     * @return the value of BC_TRANSACTON.INDEX_IN_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getIndexInBlock() {
        return indexInBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.INDEX_IN_BLOCK
     *
     * @param indexInBlock the value for BC_TRANSACTON.INDEX_IN_BLOCK
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setIndexInBlock(Integer indexInBlock) {
        this.indexInBlock = indexInBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.EXT_COMMENTS
     *
     * @return the value of BC_TRANSACTON.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getExtComments() {
        return extComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.EXT_COMMENTS
     *
     * @param extComments the value for BC_TRANSACTON.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setExtComments(String extComments) {
        this.extComments = extComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.CREATE_TIME
     *
     * @return the value of BC_TRANSACTON.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.CREATE_TIME
     *
     * @param createTime the value for BC_TRANSACTON.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.UPDATE_TIME
     *
     * @return the value of BC_TRANSACTON.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.UPDATE_TIME
     *
     * @param updateTime the value for BC_TRANSACTON.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCTransacton other = (BCTransacton) that;
        return (this.getTxid() == null ? other.getTxid() == null : this.getTxid().equals(other.getTxid()))
            && (this.getBversion() == null ? other.getBversion() == null : this.getBversion().equals(other.getBversion()))
            && (this.getHashMerkleRoot() == null ? other.getHashMerkleRoot() == null : this.getHashMerkleRoot().equals(other.getHashMerkleRoot()))
            && (this.getBlockHeight() == null ? other.getBlockHeight() == null : this.getBlockHeight().equals(other.getBlockHeight()))
            && (this.getAddressInCount() == null ? other.getAddressInCount() == null : this.getAddressInCount().equals(other.getAddressInCount()))
            && (this.getAddressOutCount() == null ? other.getAddressOutCount() == null : this.getAddressOutCount().equals(other.getAddressOutCount()))
            && (this.getPropCount() == null ? other.getPropCount() == null : this.getPropCount().equals(other.getPropCount()))
            && (this.getTxStatus() == null ? other.getTxStatus() == null : this.getTxStatus().equals(other.getTxStatus()))
            && (this.getIndexInBlock() == null ? other.getIndexInBlock() == null : this.getIndexInBlock().equals(other.getIndexInBlock()))
            && (this.getExtComments() == null ? other.getExtComments() == null : this.getExtComments().equals(other.getExtComments()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTxid() == null) ? 0 : getTxid().hashCode());
        result = prime * result + ((getBversion() == null) ? 0 : getBversion().hashCode());
        result = prime * result + ((getHashMerkleRoot() == null) ? 0 : getHashMerkleRoot().hashCode());
        result = prime * result + ((getBlockHeight() == null) ? 0 : getBlockHeight().hashCode());
        result = prime * result + ((getAddressInCount() == null) ? 0 : getAddressInCount().hashCode());
        result = prime * result + ((getAddressOutCount() == null) ? 0 : getAddressOutCount().hashCode());
        result = prime * result + ((getPropCount() == null) ? 0 : getPropCount().hashCode());
        result = prime * result + ((getTxStatus() == null) ? 0 : getTxStatus().hashCode());
        result = prime * result + ((getIndexInBlock() == null) ? 0 : getIndexInBlock().hashCode());
        result = prime * result + ((getExtComments() == null) ? 0 : getExtComments().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bversion=").append(bversion);
        sb.append(", hashMerkleRoot=").append(hashMerkleRoot);
        sb.append(", blockHeight=").append(blockHeight);
        sb.append(", addressInCount=").append(addressInCount);
        sb.append(", addressOutCount=").append(addressOutCount);
        sb.append(", propCount=").append(propCount);
        sb.append(", txStatus=").append(txStatus);
        sb.append(", indexInBlock=").append(indexInBlock);
        sb.append(", extComments=").append(extComments);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}