package org.brewchain.backend.ordbgens.bc.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class BCTransactonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON.TXID
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    private String txid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON.TXID
     *
     * @return the value of BC_TRANSACTON.TXID
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON.TXID
     *
     * @param txid the value for BC_TRANSACTON.TXID
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    public void setTxid(String txid) {
        this.txid = txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCTransactonKey other = (BCTransactonKey) that;
        return (this.getTxid() == null ? other.getTxid() == null : this.getTxid().equals(other.getTxid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTxid() == null) ? 0 : getTxid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON
     *
     * @mbggenerated Tue Aug 21 20:51:20 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", txid=").append(txid);
        sb.append("]");
        return sb.toString();
    }
}