package org.brewchain.backend.ordbgens.bc.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="BC_TRANSACTON_ADDRESS")
@AllArgsConstructor
@NoArgsConstructor
public class BCTransactonAddress extends BCTransactonAddressKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.LOG_UUID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String logUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String bversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.PREV_TXID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String prevTxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Integer indexInTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.ADDR_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String addrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.NEXT_SCRIPT_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String nextScriptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.SVALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal svalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.FEE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.TAX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private String extComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_TRANSACTON_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.LOG_UUID
     *
     * @return the value of BC_TRANSACTON_ADDRESS.LOG_UUID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getLogUuid() {
        return logUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.LOG_UUID
     *
     * @param logUuid the value for BC_TRANSACTON_ADDRESS.LOG_UUID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setLogUuid(String logUuid) {
        this.logUuid = logUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.ADDRESS
     *
     * @return the value of BC_TRANSACTON_ADDRESS.ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.ADDRESS
     *
     * @param address the value for BC_TRANSACTON_ADDRESS.ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.BVERSION
     *
     * @return the value of BC_TRANSACTON_ADDRESS.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getBversion() {
        return bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.BVERSION
     *
     * @param bversion the value for BC_TRANSACTON_ADDRESS.BVERSION
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setBversion(String bversion) {
        this.bversion = bversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.PREV_TXID
     *
     * @return the value of BC_TRANSACTON_ADDRESS.PREV_TXID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getPrevTxid() {
        return prevTxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.PREV_TXID
     *
     * @param prevTxid the value for BC_TRANSACTON_ADDRESS.PREV_TXID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setPrevTxid(String prevTxid) {
        this.prevTxid = prevTxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.INDEX_IN_TX
     *
     * @return the value of BC_TRANSACTON_ADDRESS.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Integer getIndexInTx() {
        return indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.INDEX_IN_TX
     *
     * @param indexInTx the value for BC_TRANSACTON_ADDRESS.INDEX_IN_TX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setIndexInTx(Integer indexInTx) {
        this.indexInTx = indexInTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.ADDR_TYPE
     *
     * @return the value of BC_TRANSACTON_ADDRESS.ADDR_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getAddrType() {
        return addrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.ADDR_TYPE
     *
     * @param addrType the value for BC_TRANSACTON_ADDRESS.ADDR_TYPE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setAddrType(String addrType) {
        this.addrType = addrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.NEXT_SCRIPT_ID
     *
     * @return the value of BC_TRANSACTON_ADDRESS.NEXT_SCRIPT_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getNextScriptId() {
        return nextScriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.NEXT_SCRIPT_ID
     *
     * @param nextScriptId the value for BC_TRANSACTON_ADDRESS.NEXT_SCRIPT_ID
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setNextScriptId(String nextScriptId) {
        this.nextScriptId = nextScriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.SVALUE
     *
     * @return the value of BC_TRANSACTON_ADDRESS.SVALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getSvalue() {
        return svalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.SVALUE
     *
     * @param svalue the value for BC_TRANSACTON_ADDRESS.SVALUE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setSvalue(BigDecimal svalue) {
        this.svalue = svalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.FEE
     *
     * @return the value of BC_TRANSACTON_ADDRESS.FEE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.FEE
     *
     * @param fee the value for BC_TRANSACTON_ADDRESS.FEE
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.TAX
     *
     * @return the value of BC_TRANSACTON_ADDRESS.TAX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.TAX
     *
     * @param tax the value for BC_TRANSACTON_ADDRESS.TAX
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.EXT_COMMENTS
     *
     * @return the value of BC_TRANSACTON_ADDRESS.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public String getExtComments() {
        return extComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.EXT_COMMENTS
     *
     * @param extComments the value for BC_TRANSACTON_ADDRESS.EXT_COMMENTS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setExtComments(String extComments) {
        this.extComments = extComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.CREATE_TIME
     *
     * @return the value of BC_TRANSACTON_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.CREATE_TIME
     *
     * @param createTime the value for BC_TRANSACTON_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_TRANSACTON_ADDRESS.UPDATE_TIME
     *
     * @return the value of BC_TRANSACTON_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_TRANSACTON_ADDRESS.UPDATE_TIME
     *
     * @param updateTime the value for BC_TRANSACTON_ADDRESS.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCTransactonAddress other = (BCTransactonAddress) that;
        return (this.getTxid() == null ? other.getTxid() == null : this.getTxid().equals(other.getTxid()))
            && (this.getLogUuid() == null ? other.getLogUuid() == null : this.getLogUuid().equals(other.getLogUuid()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getBversion() == null ? other.getBversion() == null : this.getBversion().equals(other.getBversion()))
            && (this.getPrevTxid() == null ? other.getPrevTxid() == null : this.getPrevTxid().equals(other.getPrevTxid()))
            && (this.getIndexInTx() == null ? other.getIndexInTx() == null : this.getIndexInTx().equals(other.getIndexInTx()))
            && (this.getAddrType() == null ? other.getAddrType() == null : this.getAddrType().equals(other.getAddrType()))
            && (this.getNextScriptId() == null ? other.getNextScriptId() == null : this.getNextScriptId().equals(other.getNextScriptId()))
            && (this.getSvalue() == null ? other.getSvalue() == null : this.getSvalue().equals(other.getSvalue()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getTax() == null ? other.getTax() == null : this.getTax().equals(other.getTax()))
            && (this.getExtComments() == null ? other.getExtComments() == null : this.getExtComments().equals(other.getExtComments()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTxid() == null) ? 0 : getTxid().hashCode());
        result = prime * result + ((getLogUuid() == null) ? 0 : getLogUuid().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getBversion() == null) ? 0 : getBversion().hashCode());
        result = prime * result + ((getPrevTxid() == null) ? 0 : getPrevTxid().hashCode());
        result = prime * result + ((getIndexInTx() == null) ? 0 : getIndexInTx().hashCode());
        result = prime * result + ((getAddrType() == null) ? 0 : getAddrType().hashCode());
        result = prime * result + ((getNextScriptId() == null) ? 0 : getNextScriptId().hashCode());
        result = prime * result + ((getSvalue() == null) ? 0 : getSvalue().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getTax() == null) ? 0 : getTax().hashCode());
        result = prime * result + ((getExtComments() == null) ? 0 : getExtComments().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_TRANSACTON_ADDRESS
     *
     * @mbggenerated Tue Aug 21 20:42:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logUuid=").append(logUuid);
        sb.append(", address=").append(address);
        sb.append(", bversion=").append(bversion);
        sb.append(", prevTxid=").append(prevTxid);
        sb.append(", indexInTx=").append(indexInTx);
        sb.append(", addrType=").append(addrType);
        sb.append(", nextScriptId=").append(nextScriptId);
        sb.append(", svalue=").append(svalue);
        sb.append(", fee=").append(fee);
        sb.append(", tax=").append(tax);
        sb.append(", extComments=").append(extComments);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}